// Generated by bun-plugin-auto-imports

// This file injects auto-imported functions into the global scope
// Import this file early in your application startup

import * as autoImports from './index'

// Inject into globalThis for runtime access
Object.assign(globalThis, autoImports)

// TypeScript declarations
declare global {
  const basemapStyle: typeof autoImports.basemapStyle
  const DARK: typeof autoImports.DARK
  const LIGHT: typeof autoImports.LIGHT
  const cartHandlers: typeof autoImports.cartHandlers
  const codeSheet: typeof autoImports.codeSheet
  const increment: typeof autoImports.increment
  const decrement: typeof autoImports.decrement
  const reset: typeof autoImports.reset
  const count: typeof autoImports.count
  const startTracking: typeof autoImports.startTracking
  const toggleDark: typeof autoImports.toggleDark
  const isDark: typeof autoImports.isDark
  const preferredDark: typeof autoImports.preferredDark
  const basemap: typeof autoImports.basemap
  const keepSized: typeof autoImports.keepSized
  const placeMap: typeof autoImports.placeMap
  const placeHandlers: typeof autoImports.placeHandlers
  const csrfToken: typeof autoImports.csrfToken
  const visitorToken: typeof autoImports.visitorToken
  const authToken: typeof autoImports.authToken
  const setAuthToken: typeof autoImports.setAuthToken
  const clearAuthToken: typeof autoImports.clearAuthToken
  const send: typeof autoImports.send
  const money: typeof autoImports.money
  const apiGet: typeof autoImports.apiGet
  const me: typeof autoImports.me
  const forgetMe: typeof autoImports.forgetMe
  const may: typeof autoImports.may
}

export {}
