import { mkdirSync, readdirSync, rmSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import process from 'node:process'
import { defineCommand, log } from '@stacksjs/cli'
import { db } from '@stacksjs/database'

/**
 * Write one page per business into `resources/views/places/`.
 *
 * The obvious shape for this is a single dynamic view, `places/[slug].stx`,
 * reading the slug from the route. It does not work: on the per-request render
 * path, a value produced by a top-level `await` in `<script server>` never
 * reaches the template, and neither does one returned by a function imported
 * from `app/`. Both arrive empty with no error, so the page renders its whole
 * layout around missing data and reads as a restaurant with nothing in it. The
 * same code in a view that renders once, like the home page, works.
 *
 * So each business gets a view that renders once. Every generated file is six
 * lines that name a slug and include one shared partial, which is where the
 * markup actually lives - there is no duplicated template, just duplicated
 * entry points, and the URLs stay clean.
 *
 * Run after seeding. `buddy seed:demo` calls it, and so does the deploy.
 */
export default defineCommand((cli) => {
  cli
    .command('build:places', 'Generate a page for each seeded business')
    .action(async () => {
      const businesses = await db.selectFrom('businesses').select(['slug', 'name']).execute() as Array<{ slug: string, name: string }>
      const directory = join(process.cwd(), 'resources/views/places')

      // Rebuilt wholesale so a business removed from the seed loses its page
      // rather than lingering as a route to data that is gone.
      rmSync(directory, { recursive: true, force: true })
      mkdirSync(directory, { recursive: true })

      for (const business of businesses)
        writeFileSync(join(directory, `${business.slug}.stx`), pageFor(business.slug))

      const written = readdirSync(directory).length

      // Printable QR sheets, one per business that seats people. Same reason
      // as the place pages: the codes are rendered server-side, and a view that
      // reads its subject off the request cannot do that.
      const codeDirectory = join(process.cwd(), 'resources/views/codes')
      rmSync(codeDirectory, { recursive: true, force: true })
      mkdirSync(codeDirectory, { recursive: true })

      const seating = await db.selectFrom('businesses')
        .where('offers_dine_in', '=', 1)
        .select(['slug'])
        .execute() as Array<{ slug: string }>

      for (const business of seating)
        writeFileSync(join(codeDirectory, `${business.slug}.stx`), codeSheetFor(business.slug))

      log.success(`Wrote ${written} place pages and ${seating.length} QR sheets`)
    })
})

/*
 * The document skeleton lives here rather than in the partial.
 *
 * stx stamps the setup marker onto the `<body>` tag of the page it is
 * compiling. With the body inside an included partial it found none, so the
 * page's signals never hydrated: the script ran, the fetches returned, and not
 * one binding applied. Nothing warned; the page simply rendered its static half.
 */
function pageFor(slug: string): string {
  return `<script server>
// Generated by \`buddy build:places\`. Do not edit this file; the markup is in
// resources/partials/place-body.stx and the data shaping in
// app/Actions/Business/place-view.ts.
// The partial below calls \`t\`, not this file, which the linter cannot see
// from here.
// eslint-disable-next-line unused-imports/no-unused-imports
import { currentLocale, t } from '../../../app/Actions/Locale/translate'
import { placeViewModel } from '../../../app/Actions/Business/place-view'
import { businessBySlug } from '../../../app/Actions/Business/search'

const vm = placeViewModel(await businessBySlug('${slug}'), currentLocale())

/*
 * The strings the shared partial's script writes, already translated. Built
 * here rather than inline in the partial, the same way the rest of this app
 * hands the client a payload: stx sometimes reads an inline JSON.stringify as
 * a client expression and leaves the literal in the attribute.
 */
const clientStrings = JSON.stringify({
  'business.save': t('business.save'),
  'business.saved': t('business.saved'),
  'review.untitled': t('review.untitled'),
  'review.helpful': t('review.helpful'),
  'review.helpful_yours': t('review.helpful_yours'),
  'review.helpful_count': t('review.helpful_count', { count: '{count}' }),
  'place.joined_head': t('place.joined_head', { date: '{date}' }),
  'place.cadence_weekly': t('place.cadence_weekly'),
  'place.cadence_biweekly': t('place.cadence_biweekly'),
  'place.cadence_monthly': t('place.cadence_monthly'),
  'place.rating_summary': t('place.rating_summary', { average: '{average}', count: '{count}' }),
  'review.dishes_label': t('review.dishes_label', { dishes: '{dishes}' }),
  'review.verified': t('review.verified'),
  'review.stars_of_five': t('review.stars_of_five', { count: '{count}' }),
  'place.every_day': t('place.every_day', { day: '{day}' }),
  'place.box_ready_on': t('place.box_ready_on', { price: '{price}', day: '{day}' }),
})

// Read by the head partial.
const pageTitle = vm.pageTitle
const pageDescription = vm.pageDescription
const canonicalPath = vm.canonicalPath
</script>

<!DOCTYPE html>
<html lang="{{ locale }}">
  <head>
    @include('head')
  </head>

  <body>
    @include('chrome')
    @include('place-body')

    <script client>
      import { placeHandlers, placeMap } from '../../functions/place-page'
      // \`money\` is used by the markup rather than by this script, which the
      // linter cannot see from here.
      // eslint-disable-next-line unused-imports/no-unused-imports
      import { money } from '../../functions/session'
      import 'ts-maps/styles.css'

      // Read off the element rather than interpolated: a raw echo inside
      // <script client> is not processed by the views build, so the page
      // compiles in the dev server and fails in the build.
      const mapEl = document.getElementById('place-map')
      const point = mapEl ? JSON.parse(mapEl.dataset.point || '{}') : {}

      /*
       * The signals are declared here, in the page's own script, because that
       * is the only place stx looks when it builds a page's setup. Handed back
       * from a factory and destructured, they are invisible to it and every
       * binding on the page silently does nothing.
       *
       * Grouped into a few objects rather than two dozen separate signals, to
       * keep this block short: it is repeated in all 280 generated views.
       */
      const saved = state(false)
      const reviews = state([])
      const stats = state(null)
      const canReview = state(false)
      const loadingReviews = state(true)
      const composer = state({ rating: 0, authorName: '', title: '', body: '', dishes: '', error: '' })
      const plans = state([])
      const share = state({ plan: null, name: '', fulfilment: 'pickup', address: '', error: '', joined: null })
      const claim = state({ open: false, name: '', email: '', message: '', error: '', sent: false })

      const wroteOne = derived(() => reviews().some(review => review.mine))

      const {
        setComposer, setShare, setClaim,
        toggleSave, postReview, vote, joinShare, sendClaim,
        stars, cadence, barsFrom, say, helpfulCount, joinedLine, everyDay, boxLine,
        ratingSummary, dishesLine, starLabel, load,
      } = placeHandlers({ slug: point.slug || '', saved, reviews, stats, canReview, loadingReviews, composer, plans, share, claim })

      placeMap(mapEl, point)
      load()
    </script>

  </body>
</html>
`
}

function codeSheetFor(slug: string): string {
  return `<script server>
// Generated by \`buddy build:places\`. Do not edit this file.
import { currentLocale, t } from '../../../app/Actions/Locale/translate'
import { tableCodesFor } from '../../../app/Actions/Dine/tables'

const origin = process.env.APP_URL ? \`https://\${process.env.APP_URL}\` : 'http://localhost:3140'
const codes = await tableCodesFor('${slug}', origin) ?? []

const pageTitle = t('meta.codes_title')
const pageDescription = t('meta.codes_description')
const canonicalPath = '/codes/${slug}'
</script>

@include('code-sheet')
`
}
