import { mkdirSync, readdirSync, rmSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import process from 'node:process'
import { defineCommand, log } from '@stacksjs/cli'
import { db } from '@stacksjs/database'

/**
 * Write one page per business into `resources/views/places/`.
 *
 * The obvious shape for this is a single dynamic view, `places/[slug].stx`,
 * reading the slug from the route. It does not work: on the per-request render
 * path, a value produced by a top-level `await` in `<script server>` never
 * reaches the template, and neither does one returned by a function imported
 * from `app/`. Both arrive empty with no error, so the page renders its whole
 * layout around missing data and reads as a restaurant with nothing in it. The
 * same code in a view that renders once, like the home page, works.
 *
 * So each business gets a view that renders once. Every generated file is six
 * lines that name a slug and include one shared partial, which is where the
 * markup actually lives - there is no duplicated template, just duplicated
 * entry points, and the URLs stay clean.
 *
 * Run after seeding. `buddy seed:demo` calls it, and so does the deploy.
 */
export default defineCommand((cli) => {
  cli
    .command('build:places', 'Generate a page for each seeded business')
    .action(async () => {
      const businesses = await db.selectFrom('businesses').select(['slug', 'name']).execute() as Array<{ slug: string, name: string }>
      const directory = join(process.cwd(), 'resources/views/places')

      // Rebuilt wholesale so a business removed from the seed loses its page
      // rather than lingering as a route to data that is gone.
      rmSync(directory, { recursive: true, force: true })
      mkdirSync(directory, { recursive: true })

      for (const business of businesses)
        writeFileSync(join(directory, `${business.slug}.stx`), pageFor(business.slug))

      const written = readdirSync(directory).length

      // Printable QR sheets, one per business that seats people. Same reason
      // as the place pages: the codes are rendered server-side, and a view that
      // reads its subject off the request cannot do that.
      const codeDirectory = join(process.cwd(), 'resources/views/codes')
      rmSync(codeDirectory, { recursive: true, force: true })
      mkdirSync(codeDirectory, { recursive: true })

      const seating = await db.selectFrom('businesses')
        .where('offers_dine_in', '=', 1)
        .select(['slug'])
        .execute() as Array<{ slug: string }>

      for (const business of seating)
        writeFileSync(join(codeDirectory, `${business.slug}.stx`), codeSheetFor(business.slug))

      log.success(`Wrote ${written} place pages and ${seating.length} QR sheets`)
    })
})

function pageFor(slug: string): string {
  return `<script server>
// Generated by \`buddy build:places\`. Do not edit this file; the markup is in
// resources/partials/place-body.stx and the data shaping in
// app/Actions/Business/place-view.ts.
import { placeViewModel } from '../../../app/Actions/Business/place-view'
import { businessBySlug } from '../../../app/Actions/Business/search'

const vm = placeViewModel(await businessBySlug('${slug}'))

// Read by the head partial.
const pageTitle = vm.pageTitle
const pageDescription = vm.pageDescription
const canonicalPath = vm.canonicalPath
</script>

@include('place-body')
`
}

function codeSheetFor(slug: string): string {
  return `<script server>
// Generated by \`buddy build:places\`. Do not edit this file.
import { tableCodesFor } from '../../../app/Actions/Dine/tables'

const origin = process.env.APP_URL ? \`https://\${process.env.APP_URL}\` : 'http://localhost:3140'
const codes = await tableCodesFor('${slug}', origin) ?? []

const pageTitle = 'Table codes - Smakelo'
const pageDescription = 'Printable codes for every table.'
const canonicalPath = '/codes/${slug}'
</script>

@include('code-sheet')
`
}
