import { mkdirSync, readdirSync, rmSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import process from 'node:process'
import { defineCommand, log } from '@stacksjs/cli'
import { db } from '@stacksjs/database'

/**
 * Write one page per business into `resources/views/places/`.
 *
 * The obvious shape for this is a single dynamic view, `places/[slug].stx`,
 * reading the slug from the route. It does not work: on the per-request render
 * path, a value produced by a top-level `await` in `<script server>` never
 * reaches the template, and neither does one returned by a function imported
 * from `app/`. Both arrive empty with no error, so the page renders its whole
 * layout around missing data and reads as a restaurant with nothing in it. The
 * same code in a view that renders once, like the home page, works.
 *
 * So each business gets a view that renders once. Every generated file is six
 * lines that name a slug and include one shared partial, which is where the
 * markup actually lives - there is no duplicated template, just duplicated
 * entry points, and the URLs stay clean.
 *
 * Run after seeding. `buddy seed:demo` calls it, and so does the deploy.
 */
export default defineCommand((cli) => {
  cli
    .command('build:places', 'Generate a page for each seeded business')
    .action(async () => {
      const businesses = await db.selectFrom('businesses').select(['slug', 'name']).execute() as Array<{ slug: string, name: string }>
      const directory = join(process.cwd(), 'resources/views/places')

      // Rebuilt wholesale so a business removed from the seed loses its page
      // rather than lingering as a route to data that is gone.
      rmSync(directory, { recursive: true, force: true })
      mkdirSync(directory, { recursive: true })

      for (const business of businesses)
        writeFileSync(join(directory, `${business.slug}.stx`), pageFor(business.slug))

      const written = readdirSync(directory).length
      log.success(`Wrote ${written} place pages to resources/views/places/`)
    })
})

function pageFor(slug: string): string {
  return `<script server>
// Generated by \`buddy build:places\`. Do not edit this file; the markup is in
// resources/partials/place-body.stx and the data shaping in
// app/Actions/Business/place-view.ts.
import { placeViewModel } from '../../../app/Actions/Business/place-view'
import { businessBySlug } from '../../../app/Actions/Business/search'

const vm = placeViewModel(await businessBySlug('${slug}'))

// Read by the head partial.
const pageTitle = vm.pageTitle
const pageDescription = vm.pageDescription
const canonicalPath = vm.canonicalPath
</script>

@include('place-body')
`
}
