-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "campaign_sends" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "campaign_id" INTEGER not null REFERENCES "campaigns"("id"),
  "subscriber_id" INTEGER REFERENCES "subscribers"("id"),
  "email_list_id" INTEGER REFERENCES "email_lists"("id"),
  "status" TEXT CHECK ("status" IN ('queued', 'deferred', 'sending', 'sent', 'delivered', 'failed', 'undelivered', 'bounced', 'complained', 'suppressed', 'cancelled')) not null default 'queued',
  "channel" TEXT CHECK ("channel" IN ('email', 'sms', 'push')) not null default 'email',
  "recipient" TEXT not null,
  "idempotency_key" TEXT not null,
  "provider_message_id" TEXT,
  "error" TEXT,
  "sent_at" TEXT,
  "opened_at" TEXT,
  "clicked_at" TEXT,
  "delivered_at" TEXT,
  "failed_at" TEXT,
  "segments" INTEGER,
  "cost" INTEGER,
  "metadata" TEXT,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "campaign_variant_id" INTEGER REFERENCES "campaign_variants"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "campaign_sends_idempotency_unique" ON "campaign_sends" ("idempotency_key");
CREATE UNIQUE INDEX IF NOT EXISTS "campaign_sends_uuid_unique" ON "campaign_sends" ("uuid");
