-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "ledger_entries" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "party_type" TEXT CHECK ("party_type" IN ('business', 'courier', 'platform')) not null,
  "party_id" INTEGER not null,
  "kind" TEXT CHECK ("kind" IN ('order_revenue', 'service_fee', 'delivery_fee', 'tip', 'refund', 'payout', 'adjustment')) not null,
  "amount_cents" INTEGER not null default 0,
  "currency" TEXT not null default 'usd',
  "description" TEXT,
  "external_reference" TEXT,
  "order_id" INTEGER REFERENCES "orders"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "ledger_entries_uuid_unique" ON "ledger_entries" ("uuid");
