-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "business_photos" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "url" TEXT not null,
  "caption" TEXT,
  "credit" TEXT,
  "position" INTEGER not null default 0,
  "alt" TEXT,
  "business_id" INTEGER REFERENCES "businesses"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "business_photos_uuid_unique" ON "business_photos" ("uuid");
