-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "review_photos" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "url" TEXT not null,
  "position" INTEGER not null default 0,
  "alt" TEXT,
  "business_review_id" INTEGER REFERENCES "business_reviews"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "review_photos_uuid_unique" ON "review_photos" ("uuid");
