-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "taggable_models" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "tag_id" INTEGER not null REFERENCES "taggables"("id"),
  "taggable_id" INTEGER not null,
  "taggable_type" TEXT not null,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "taggable_models_owner_unique" ON "taggable_models" ("tag_id", "taggable_id", "taggable_type");
CREATE INDEX IF NOT EXISTS "taggable_models_target_index" ON "taggable_models" ("taggable_id", "taggable_type");
