-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "csa_subscriptions" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "status" TEXT CHECK ("status" IN ('active', 'paused', 'cancelled')) not null default 'active',
  "fulfilment" TEXT CHECK ("fulfilment" IN ('pickup', 'delivery')) not null default 'pickup',
  "delivery_address" TEXT,
  "next_box_at" TEXT,
  "paused_until" TEXT,
  "boxes_delivered" INTEGER default 0,
  "note" TEXT,
  "csa_plan_id" INTEGER REFERENCES "csa_plans"("id"),
  "customer_id" INTEGER REFERENCES "customers"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "csa_subscriptions_uuid_unique" ON "csa_subscriptions" ("uuid");
