-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "addresses" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "label" TEXT default 'Home',
  "line" TEXT not null,
  "city" TEXT,
  "postal_code" TEXT,
  "latitude" REAL,
  "longitude" REAL,
  "notes" TEXT,
  "is_default" INTEGER default 0,
  "customer_id" INTEGER REFERENCES "customers"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "addresses_uuid_unique" ON "addresses" ("uuid");
