-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "order_item_modifiers" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "group_name" TEXT not null,
  "name" TEXT not null,
  "price_delta_cents" INTEGER not null default 0,
  "quantity" INTEGER not null default 1,
  "order_item_id" INTEGER REFERENCES "order_items"("id"),
  "modifier_id" INTEGER REFERENCES "modifiers"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "order_item_modifiers_uuid_unique" ON "order_item_modifiers" ("uuid");
