-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "business_reviews" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "rating" INTEGER not null,
  "title" TEXT,
  "body" TEXT not null,
  "dishes" TEXT,
  "owner_response" TEXT,
  "owner_responded_at" TEXT,
  "helpful_count" INTEGER not null default 0,
  "is_published" INTEGER not null default 1,
  "visited_at" TEXT,
  "business_id" INTEGER REFERENCES "businesses"("id"),
  "customer_id" INTEGER REFERENCES "customers"("id"),
  "order_id" INTEGER REFERENCES "orders"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "deleted_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "business_reviews_uuid_unique" ON "business_reviews" ("uuid");
