-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "modifier_groups" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT not null,
  "description" TEXT,
  "min_selections" INTEGER not null default 0,
  "max_selections" INTEGER not null default 1,
  "allows_quantity" INTEGER not null default 0,
  "position" INTEGER not null default 0,
  "product_id" INTEGER REFERENCES "products"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "modifier_groups_uuid_unique" ON "modifier_groups" ("uuid");
