-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "review_votes" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "helpful" INTEGER not null default 1,
  "business_review_id" INTEGER REFERENCES "business_reviews"("id"),
  "customer_id" INTEGER REFERENCES "customers"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "review_votes_uuid_unique" ON "review_votes" ("uuid");
