-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "claims" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "status" TEXT CHECK ("status" IN ('pending', 'approved', 'rejected')) not null default 'pending',
  "claimant_name" TEXT not null,
  "claimant_email" TEXT not null,
  "message" TEXT,
  "decided_at" TEXT,
  "business_id" INTEGER REFERENCES "businesses"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "claims_uuid_unique" ON "claims" ("uuid");
