-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "couriers" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT not null,
  "phone" TEXT not null,
  "vehicle_number" TEXT not null,
  "license" TEXT not null,
  "status" TEXT CHECK ("status" IN ('active', 'on_delivery', 'on_break', 'offline')) default 'active',
  "latitude" INTEGER,
  "longitude" INTEGER,
  "heading" INTEGER,
  "speed" INTEGER default 0,
  "last_ping_at" TEXT,
  "user_id" INTEGER REFERENCES "users"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "couriers_uuid_unique" ON "couriers" ("uuid");
