-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "csa_plans" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT not null,
  "description" TEXT,
  "price_cents" INTEGER not null,
  "cadence" TEXT CHECK ("cadence" IN ('weekly', 'biweekly', 'monthly')) not null default 'weekly',
  "feeds" TEXT,
  "day_of_week" INTEGER not null default 3,
  "offers_delivery" INTEGER default 0,
  "is_active" INTEGER default 1,
  "business_id" INTEGER REFERENCES "businesses"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "csa_plans_uuid_unique" ON "csa_plans" ("uuid");
