-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
PRAGMA foreign_keys=OFF;
BEGIN;
CREATE TABLE "_qb_tmp_ledger_entries" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "party_type" TEXT CHECK ("party_type" IN ('business', 'courier', 'platform', 'tax')) not null,
  "party_id" INTEGER not null,
  "kind" TEXT CHECK ("kind" IN ('order_revenue', 'service_fee', 'delivery_fee', 'tip', 'tax_collected', 'tax_withheld', 'refund', 'payout', 'adjustment')) not null,
  "amount_cents" INTEGER not null default 0,
  "currency" TEXT not null default 'usd',
  "description" TEXT,
  "external_reference" TEXT,
  "order_id" INTEGER REFERENCES "orders"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
INSERT INTO "_qb_tmp_ledger_entries" ("id", "party_type", "party_id", "kind", "amount_cents", "currency", "description", "external_reference", "order_id", "created_at", "updated_at", "uuid") SELECT "id", "party_type", "party_id", "kind", "amount_cents", "currency", "description", "external_reference", "order_id", "created_at", "updated_at", "uuid" FROM "ledger_entries";
DROP TABLE "ledger_entries";
ALTER TABLE "_qb_tmp_ledger_entries" RENAME TO "ledger_entries";
CREATE UNIQUE INDEX IF NOT EXISTS "ledger_entries_uuid_unique" ON "ledger_entries" ("uuid");
PRAGMA foreign_key_check;
COMMIT;
PRAGMA foreign_keys=ON;
