-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "pages" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "title" TEXT not null,
  "slug" TEXT,
  "path" TEXT,
  "parent_id" INTEGER,
  "template" TEXT not null,
  "blocks" TEXT,
  "meta_description" TEXT,
  "status" TEXT CHECK ("status" IN ('draft', 'published', 'scheduled', 'archived')) default 'draft',
  "scheduled_at" TEXT,
  "views" INTEGER default 0,
  "published_at" TEXT,
  "conversions" INTEGER default 0,
  "author_id" INTEGER REFERENCES "authors"("id"),
  "site_id" INTEGER REFERENCES "sites"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "pages_site_path_unique" ON "pages" ("site_id", "path");
CREATE UNIQUE INDEX IF NOT EXISTS "pages_uuid_unique" ON "pages" ("uuid");
