-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "notification_deliveries" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "user_id" INTEGER REFERENCES "users"("id"),
  "channel" TEXT not null,
  "recipient" TEXT not null,
  "subject" TEXT,
  "body" TEXT not null,
  "status" TEXT not null default 'pending',
  "error" TEXT,
  "metadata" TEXT,
  "sent_at" TEXT,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT
);
