-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "orders" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "status" TEXT not null,
  "total_amount" INTEGER not null,
  "currency" TEXT not null default 'USD',
  "tax_amount" INTEGER default 0,
  "discount_amount" INTEGER default 0,
  "delivery_fee" INTEGER default 0,
  "tip_amount" INTEGER default 0,
  "order_type" TEXT not null,
  "delivery_address" TEXT,
  "special_instructions" TEXT,
  "estimated_delivery_time" TEXT,
  "tracking_token" TEXT,
  "delivery_latitude" INTEGER,
  "delivery_longitude" INTEGER,
  "applied_coupon_id" TEXT,
  "service_fee_cents" INTEGER not null default 0,
  "subtotal_cents" INTEGER not null default 0,
  "scheduled_for" TEXT,
  "business_id" INTEGER REFERENCES "businesses"("id"),
  "customer_id" INTEGER REFERENCES "customers"("id"),
  "coupon_id" INTEGER REFERENCES "coupons"("id"),
  "table_id" INTEGER REFERENCES "tables"("id"),
  "tab_id" INTEGER REFERENCES "tabs"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "orders_tracking_token_unique" ON "orders" ("tracking_token");
CREATE UNIQUE INDEX IF NOT EXISTS "orders_uuid_unique" ON "orders" ("uuid");
