-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "tables" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "label" TEXT not null,
  "qr_token" TEXT not null,
  "seats" INTEGER not null default 2,
  "is_active" INTEGER not null default 1,
  "business_id" INTEGER REFERENCES "businesses"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "tables_qr_token_unique" ON "tables" ("qr_token");
CREATE UNIQUE INDEX IF NOT EXISTS "tables_uuid_unique" ON "tables" ("uuid");
