-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "taggables" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT not null,
  "slug" TEXT not null,
  "description" TEXT,
  "order" INTEGER not null default 0,
  "is_active" INTEGER not null default 1,
  "taggable_id" INTEGER,
  "taggable_type" TEXT not null,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT
);
CREATE INDEX IF NOT EXISTS "taggables_target_index" ON "taggables" ("taggable_id", "taggable_type");
CREATE UNIQUE INDEX IF NOT EXISTS "taggables_type_slug_unique" ON "taggables" ("taggable_type", "slug");
