-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "business_hours" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "day_of_week" INTEGER not null,
  "opens_at" INTEGER not null,
  "closes_at" INTEGER not null,
  "is_closed" INTEGER not null default 0,
  "business_id" INTEGER REFERENCES "businesses"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "business_hours_uuid_unique" ON "business_hours" ("uuid");
