-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
PRAGMA foreign_keys=OFF;
BEGIN;
CREATE TABLE "_qb_tmp_businesses" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT not null,
  "slug" TEXT not null,
  "type" TEXT CHECK ("type" IN ('restaurant', 'cafe', 'farm', 'bakery', 'bar', 'grocery', 'home_kitchen')) not null default 'restaurant',
  "description" TEXT,
  "cuisine" TEXT,
  "price_tier" INTEGER default 2,
  "address" TEXT not null,
  "city" TEXT not null,
  "postal_code" TEXT,
  "latitude" REAL not null,
  "longitude" REAL not null,
  "phone" TEXT,
  "website" TEXT,
  "hero_image" TEXT,
  "is_partner" INTEGER not null default 0,
  "is_claimed" INTEGER not null default 0,
  "offers_delivery" INTEGER not null default 0,
  "offers_pickup" INTEGER not null default 0,
  "offers_dine_in" INTEGER not null default 0,
  "offers_shop" INTEGER not null default 0,
  "self_delivery" INTEGER not null default 0,
  "delivery_radius_meters" INTEGER not null default 8000,
  "minimum_order_cents" INTEGER not null default 0,
  "prep_time_minutes" INTEGER not null default 20,
  "rating_average" INTEGER not null default 0,
  "rating_count" INTEGER not null default 0,
  "source" TEXT CHECK ("source" IN ('fsq', 'osm', 'curated', 'partner')) not null default 'curated',
  "source_id" TEXT,
  "market_id" INTEGER REFERENCES "markets"("id"),
  "team_id" INTEGER REFERENCES "teams"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "deleted_at" TEXT,
  "uuid" TEXT
);
INSERT INTO "_qb_tmp_businesses" ("id", "name", "slug", "type", "description", "cuisine", "price_tier", "address", "city", "postal_code", "latitude", "longitude", "phone", "website", "hero_image", "is_partner", "is_claimed", "offers_delivery", "offers_pickup", "offers_dine_in", "offers_shop", "self_delivery", "delivery_radius_meters", "minimum_order_cents", "prep_time_minutes", "rating_average", "rating_count", "source", "source_id", "market_id", "team_id", "created_at", "updated_at", "deleted_at", "uuid") SELECT "id", "name", "slug", "type", "description", "cuisine", "price_tier", "address", "city", "postal_code", "latitude", "longitude", "phone", "website", "hero_image", "is_partner", "is_claimed", "offers_delivery", "offers_pickup", "offers_dine_in", "offers_shop", "self_delivery", "delivery_radius_meters", "minimum_order_cents", "prep_time_minutes", "rating_average", "rating_count", "source", "source_id", "market_id", "team_id", "created_at", "updated_at", "deleted_at", "uuid" FROM "businesses";
DROP TABLE "businesses";
ALTER TABLE "_qb_tmp_businesses" RENAME TO "businesses";
CREATE UNIQUE INDEX IF NOT EXISTS "businesses_slug_unique" ON "businesses" ("slug");
CREATE UNIQUE INDEX IF NOT EXISTS "businesses_uuid_unique" ON "businesses" ("uuid");
PRAGMA foreign_key_check;
COMMIT;
PRAGMA foreign_keys=ON;
