-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "tabs" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "status" TEXT CHECK ("status" IN ('open', 'awaiting_payment', 'closed', 'abandoned')) not null default 'open',
  "split_mode" TEXT CHECK ("split_mode" IN ('by_item', 'even', 'single_payer')) not null default 'by_item',
  "party_size" INTEGER not null default 2,
  "opened_at" TEXT,
  "closed_at" TEXT,
  "total_cents" INTEGER not null default 0,
  "paid_cents" INTEGER not null default 0,
  "business_id" INTEGER REFERENCES "businesses"("id"),
  "table_id" INTEGER REFERENCES "tables"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "tabs_uuid_unique" ON "tabs" ("uuid");
