-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
ALTER TABLE "orders" ADD COLUMN "service_fee_cents" INTEGER not null default 0;
ALTER TABLE "orders" ADD COLUMN "subtotal_cents" INTEGER not null default 0;
ALTER TABLE "orders" ADD COLUMN "scheduled_for" TEXT;
ALTER TABLE "orders" ADD COLUMN "business_id" INTEGER REFERENCES "businesses"("id");
ALTER TABLE "orders" ADD COLUMN "table_id" INTEGER REFERENCES "tables"("id");
ALTER TABLE "orders" ADD COLUMN "tab_id" INTEGER REFERENCES "tabs"("id");
