-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "favorites" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "note" TEXT,
  "business_id" INTEGER REFERENCES "businesses"("id"),
  "customer_id" INTEGER,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "favorites_uuid_unique" ON "favorites" ("uuid");
