-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "markets" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT not null,
  "slug" TEXT not null,
  "city" TEXT not null,
  "country_code" TEXT not null default 'US',
  "currency" TEXT not null default 'usd',
  "tax_mode" TEXT CHECK ("tax_mode" IN ('inclusive', 'exclusive')) not null default 'exclusive',
  "default_tax_rate" REAL not null default 0,
  "timezone" TEXT not null default 'America/Los_Angeles',
  "locale" TEXT CHECK ("locale" IN ('en', 'de', 'nl')) not null default 'en',
  "center_latitude" REAL not null,
  "center_longitude" REAL not null,
  "is_active" INTEGER not null default 0,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "markets_slug_unique" ON "markets" ("slug");
CREATE UNIQUE INDEX IF NOT EXISTS "markets_uuid_unique" ON "markets" ("uuid");
