-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "modifiers" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT not null,
  "price_delta_cents" INTEGER not null default 0,
  "is_default" INTEGER not null default 0,
  "is_available" INTEGER not null default 1,
  "position" INTEGER not null default 0,
  "modifier_group_id" INTEGER REFERENCES "modifier_groups"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "modifiers_uuid_unique" ON "modifiers" ("uuid");
