-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
ALTER TABLE "products" ADD COLUMN "business_id" INTEGER REFERENCES "businesses"("id");
ALTER TABLE "taggables" ADD COLUMN "order" INTEGER not null default 0;
