-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
PRAGMA foreign_keys=OFF;
BEGIN;
CREATE TABLE "_qb_tmp_businesses" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT not null,
  "slug" TEXT not null,
  "type" TEXT CHECK ("type" IN ('restaurant', 'cafe', 'farm', 'bakery', 'bar', 'grocery')) not null default 'restaurant',
  "description" TEXT,
  "cuisine" TEXT,
  "price_tier" INTEGER default 2,
  "address" TEXT not null,
  "city" TEXT not null,
  "postal_code" TEXT,
  "latitude" REAL not null,
  "longitude" REAL not null,
  "phone" TEXT,
  "website" TEXT,
  "hero_image" TEXT,
  "is_partner" INTEGER not null default 0,
  "is_claimed" INTEGER not null default 0,
  "offers_delivery" INTEGER not null default 0,
  "offers_pickup" INTEGER not null default 0,
  "offers_dine_in" INTEGER not null default 0,
  "offers_shop" INTEGER not null default 0,
  "self_delivery" INTEGER not null default 0,
  "delivery_radius_meters" INTEGER not null default 8000,
  "minimum_order_cents" INTEGER not null default 0,
  "prep_time_minutes" INTEGER not null default 20,
  "rating_average" INTEGER not null default 0,
  "rating_count" INTEGER not null default 0,
  "source" TEXT CHECK ("source" IN ('fsq', 'osm', 'curated', 'partner')) not null default 'curated',
  "source_id" TEXT,
  "market_id" INTEGER REFERENCES "markets"("id"),
  "team_id" INTEGER,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "deleted_at" TEXT,
  "uuid" TEXT
);
INSERT INTO "_qb_tmp_businesses" ("id", "name", "slug", "type", "description", "cuisine", "price_tier", "address", "city", "postal_code", "latitude", "longitude", "phone", "website", "hero_image", "is_partner", "is_claimed", "offers_delivery", "offers_pickup", "offers_dine_in", "offers_shop", "self_delivery", "delivery_radius_meters", "minimum_order_cents", "prep_time_minutes", "rating_average", "rating_count", "source", "source_id", "market_id", "team_id", "created_at", "updated_at", "deleted_at", "uuid") SELECT "id", "name", "slug", "type", "description", "cuisine", "price_tier", "address", "city", "postal_code", "latitude", "longitude", "phone", "website", "hero_image", "is_partner", "is_claimed", "offers_delivery", "offers_pickup", "offers_dine_in", "offers_shop", "self_delivery", "delivery_radius_meters", "minimum_order_cents", "prep_time_minutes", "rating_average", "rating_count", "source", "source_id", "market_id", "team_id", "created_at", "updated_at", "deleted_at", "uuid" FROM "businesses";
DROP TABLE "businesses";
ALTER TABLE "_qb_tmp_businesses" RENAME TO "businesses";
CREATE UNIQUE INDEX IF NOT EXISTS "businesses_slug_unique" ON "businesses" ("slug");
CREATE UNIQUE INDEX IF NOT EXISTS "businesses_uuid_unique" ON "businesses" ("uuid");
PRAGMA foreign_key_check;
COMMIT;
PRAGMA foreign_keys=ON;
PRAGMA foreign_keys=OFF;
BEGIN;
CREATE TABLE "_qb_tmp_markets" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT not null,
  "slug" TEXT not null,
  "city" TEXT not null,
  "country_code" TEXT not null default 'US',
  "currency" TEXT not null default 'usd',
  "tax_mode" TEXT CHECK ("tax_mode" IN ('inclusive', 'exclusive')) not null default 'exclusive',
  "default_tax_rate" REAL not null default 0,
  "timezone" TEXT not null default 'America/Los_Angeles',
  "locale" TEXT CHECK ("locale" IN ('en', 'de', 'nl')) not null default 'en',
  "center_latitude" REAL not null,
  "center_longitude" REAL not null,
  "is_active" INTEGER not null default 0,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
INSERT INTO "_qb_tmp_markets" ("id", "name", "slug", "city", "country_code", "currency", "tax_mode", "default_tax_rate", "timezone", "locale", "center_latitude", "center_longitude", "is_active", "created_at", "updated_at", "uuid") SELECT "id", "name", "slug", "city", "country_code", "currency", "tax_mode", "default_tax_rate", "timezone", "locale", "center_latitude", "center_longitude", "is_active", "created_at", "updated_at", "uuid" FROM "markets";
DROP TABLE "markets";
ALTER TABLE "_qb_tmp_markets" RENAME TO "markets";
CREATE UNIQUE INDEX IF NOT EXISTS "markets_slug_unique" ON "markets" ("slug");
CREATE UNIQUE INDEX IF NOT EXISTS "markets_uuid_unique" ON "markets" ("uuid");
PRAGMA foreign_key_check;
COMMIT;
PRAGMA foreign_keys=ON;
