/**
 * Real places around Gescher, imported from OpenStreetMap.
 *
 * Generated by `buddy import:places --region gescher`. Do not edit by
 * hand: the curated listings live in `businesses.ts`, which is where a
 * correction belongs.
 *
 * These businesses have agreed to nothing. They are listed and searchable and
 * that is all: no reviews, no orders, and a claim form that leads with taking
 * the listing down. Data from OpenStreetMap contributors, ODbL.
 */

import type { SeedBusiness } from './businesses'

export const OSM_LISTINGS_GESCHER: SeedBusiness[] = [
  {
    "name": "Gasthof Coesfelder Tor",
    "slug": "gescher-gasthof-coesfelder-tor",
    "type": "restaurant",
    "cuisine": "Regional",
    "description": "",
    "address": "Coesfelder Straße 34",
    "city": "Velen",
    "postalCode": "46342",
    "latitude": 51.8967,
    "longitude": 6.986764,
    "priceTier": 2,
    "region": "gescher",
    "hours": []
  },
  {
    "name": "Hotel - Restaurat Zum Tiergarten",
    "slug": "gescher-hotel-restaurat-zum-tiergarten",
    "type": "restaurant",
    "cuisine": "Regional",
    "description": "",
    "address": "Rekener Straße 48",
    "city": "Velen",
    "postalCode": "46342",
    "latitude": 51.891519,
    "longitude": 6.988054,
    "priceTier": 2,
    "region": "gescher",
    "hours": [
      {
        "day": 0,
        "open": 660,
        "close": 1380
      },
      {
        "day": 2,
        "open": 960,
        "close": 1380
      },
      {
        "day": 3,
        "open": 960,
        "close": 1380
      },
      {
        "day": 6,
        "open": 660,
        "close": 1380
      }
    ]
  },
  {
    "name": "Kremer",
    "slug": "gescher-kremer",
    "type": "bakery",
    "cuisine": "",
    "description": "",
    "address": "",
    "city": "Gescher",
    "postalCode": "",
    "latitude": 51.894406,
    "longitude": 6.987429,
    "priceTier": 2,
    "region": "gescher",
    "hours": []
  },
  {
    "name": "Gasthaus Rappers",
    "slug": "gescher-gasthaus-rappers",
    "type": "restaurant",
    "cuisine": "German",
    "description": "",
    "address": "Nordvelener Straße 133",
    "city": "Velen",
    "postalCode": "46342",
    "latitude": 51.916988,
    "longitude": 6.963287,
    "priceTier": 2,
    "region": "gescher",
    "hours": []
  },
  {
    "name": "Landgut Ritter",
    "slug": "gescher-landgut-ritter",
    "type": "restaurant",
    "cuisine": "German",
    "description": "",
    "address": "",
    "city": "Gescher",
    "postalCode": "",
    "latitude": 52.001357,
    "longitude": 7.016897,
    "priceTier": 2,
    "region": "gescher",
    "hours": []
  },
  {
    "name": "Alte Kaiserei",
    "slug": "gescher-alte-kaiserei",
    "type": "restaurant",
    "cuisine": "",
    "description": "",
    "address": "",
    "city": "Gescher",
    "postalCode": "",
    "latitude": 51.939746,
    "longitude": 6.985221,
    "priceTier": 2,
    "region": "gescher",
    "hours": []
  },
  {
    "name": "Mensing",
    "slug": "gescher-mensing",
    "type": "bakery",
    "cuisine": "",
    "description": "",
    "address": "Lange Straße 17",
    "city": "Velen",
    "postalCode": "46342",
    "latitude": 51.887206,
    "longitude": 6.91995,
    "priceTier": 2,
    "region": "gescher",
    "hours": [
      {
        "day": 0,
        "open": 450,
        "close": 1020
      },
      {
        "day": 1,
        "open": 390,
        "close": 1080
      },
      {
        "day": 2,
        "open": 390,
        "close": 1080
      },
      {
        "day": 3,
        "open": 390,
        "close": 1080
      },
      {
        "day": 4,
        "open": 390,
        "close": 1080
      },
      {
        "day": 5,
        "open": 390,
        "close": 1080
      },
      {
        "day": 6,
        "open": 390,
        "close": 1020
      }
    ]
  },
  {
    "name": "Ludger's Stadtbäckerei",
    "slug": "gescher-ludger-s-stadtbackerei",
    "type": "bakery",
    "cuisine": "",
    "description": "",
    "address": "",
    "city": "Gescher",
    "postalCode": "",
    "latitude": 51.887239,
    "longitude": 6.919163,
    "priceTier": 2,
    "region": "gescher",
    "hours": []
  },
  {
    "name": "Eis Cafe Venezia",
    "slug": "gescher-eis-cafe-venezia",
    "type": "cafe",
    "cuisine": "Ice Cream",
    "description": "",
    "address": "Schulstraße 6",
    "city": "Velen",
    "postalCode": "46342",
    "latitude": 51.893904,
    "longitude": 6.988041,
    "priceTier": 2,
    "region": "gescher",
    "hours": []
  },
  {
    "name": "Warnsing",
    "slug": "gescher-warnsing",
    "type": "cafe",
    "cuisine": "Coffee",
    "description": "",
    "address": "",
    "city": "Gescher",
    "postalCode": "",
    "latitude": 51.917341,
    "longitude": 6.985176,
    "priceTier": 2,
    "region": "gescher",
    "hours": []
  },
  {
    "name": "Hermanshöhe",
    "slug": "gescher-hermanshohe",
    "type": "restaurant",
    "cuisine": "",
    "description": "",
    "address": "Haulingort 30",
    "city": "Legden",
    "postalCode": "48739",
    "latitude": 52.021127,
    "longitude": 7.116933,
    "priceTier": 2,
    "region": "gescher",
    "hours": [
      {
        "day": 0,
        "open": 660,
        "close": 1320
      },
      {
        "day": 1,
        "open": 660,
        "close": 1320
      },
      {
        "day": 2,
        "open": 660,
        "close": 1320
      },
      {
        "day": 3,
        "open": 660,
        "close": 1320
      },
      {
        "day": 4,
        "open": 660,
        "close": 1320
      },
      {
        "day": 5,
        "open": 660,
        "close": 1320
      },
      {
        "day": 6,
        "open": 660,
        "close": 1320
      }
    ]
  },
  {
    "name": "Heidekrug",
    "slug": "gescher-heidekrug",
    "type": "restaurant",
    "cuisine": "Regional",
    "description": "",
    "address": "",
    "city": "Gescher",
    "postalCode": "",
    "latitude": 51.935932,
    "longitude": 7.105817,
    "priceTier": 2,
    "region": "gescher",
    "hours": []
  },
  {
    "name": "Backhaus Ebbinghoff",
    "slug": "gescher-backhaus-ebbinghoff",
    "type": "cafe",
    "cuisine": "Cake",
    "description": "",
    "address": "Coesfelder Straße 18",
    "city": "Rosendahl",
    "postalCode": "48720",
    "latitude": 52.003476,
    "longitude": 7.129213,
    "priceTier": 2,
    "region": "gescher",
    "hours": [
      {
        "day": 1,
        "open": 315,
        "close": 1080
      },
      {
        "day": 2,
        "open": 315,
        "close": 1080
      },
      {
        "day": 3,
        "open": 315,
        "close": 1080
      },
      {
        "day": 4,
        "open": 315,
        "close": 1080
      },
      {
        "day": 5,
        "open": 315,
        "close": 1080
      }
    ]
  },
  {
    "name": "Mias Backhaus",
    "slug": "gescher-mias-backhaus",
    "type": "cafe",
    "cuisine": "Coffee",
    "description": "",
    "address": "",
    "city": "Gescher",
    "postalCode": "",
    "latitude": 51.990633,
    "longitude": 7.029396,
    "priceTier": 2,
    "region": "gescher",
    "hours": [
      {
        "day": 0,
        "open": 600,
        "close": 1140
      },
      {
        "day": 3,
        "open": 600,
        "close": 1140
      },
      {
        "day": 4,
        "open": 600,
        "close": 1140
      },
      {
        "day": 5,
        "open": 600,
        "close": 1140
      },
      {
        "day": 6,
        "open": 600,
        "close": 1140
      }
    ]
  },
  {
    "name": "Schütte",
    "slug": "gescher-schutte",
    "type": "bakery",
    "cuisine": "",
    "description": "",
    "address": "Schlesierring 6",
    "city": "Gescher",
    "postalCode": "48712",
    "latitude": 51.948138,
    "longitude": 7.015203,
    "priceTier": 2,
    "region": "gescher",
    "hours": [
      {
        "day": 0,
        "open": 420,
        "close": 660
      },
      {
        "day": 6,
        "open": 360,
        "close": 780
      }
    ]
  },
  {
    "name": "Schlüter",
    "slug": "gescher-schluter",
    "type": "bakery",
    "cuisine": "",
    "description": "",
    "address": "",
    "city": "Gescher",
    "postalCode": "",
    "latitude": 51.948639,
    "longitude": 7.001551,
    "priceTier": 2,
    "region": "gescher",
    "hours": []
  },
  {
    "name": "Essmann",
    "slug": "gescher-essmann",
    "type": "bakery",
    "cuisine": "",
    "description": "",
    "address": "Hofstraße 13",
    "city": "Gescher",
    "postalCode": "48712",
    "latitude": 51.95498,
    "longitude": 7.008055,
    "priceTier": 2,
    "region": "gescher",
    "hours": []
  },
  {
    "name": "Stadtbäckerei Schütte",
    "slug": "gescher-stadtbackerei-schutte",
    "type": "bakery",
    "cuisine": "",
    "description": "",
    "address": "",
    "city": "Gescher",
    "postalCode": "",
    "latitude": 51.956635,
    "longitude": 7.008238,
    "priceTier": 2,
    "region": "gescher",
    "hours": [
      {
        "day": 6,
        "open": 360,
        "close": 750
      }
    ]
  },
  {
    "name": "C. Gescher",
    "slug": "gescher-c-gescher",
    "type": "cafe",
    "cuisine": "Coffee",
    "description": "",
    "address": "Hauskampstraße 33",
    "city": "Gescher",
    "postalCode": "48712",
    "latitude": 51.956486,
    "longitude": 7.010255,
    "priceTier": 2,
    "region": "gescher",
    "hours": [
      {
        "day": 0,
        "open": 480,
        "close": 1080
      },
      {
        "day": 2,
        "open": 420,
        "close": 1080
      },
      {
        "day": 3,
        "open": 420,
        "close": 1080
      },
      {
        "day": 4,
        "open": 420,
        "close": 1080
      },
      {
        "day": 5,
        "open": 420,
        "close": 1080
      },
      {
        "day": 6,
        "open": 420,
        "close": 1020
      }
    ]
  },
  {
    "name": "Korfu",
    "slug": "gescher-korfu",
    "type": "restaurant",
    "cuisine": "Greek",
    "description": "",
    "address": "",
    "city": "Gescher",
    "postalCode": "",
    "latitude": 51.95514,
    "longitude": 7.007676,
    "priceTier": 2,
    "region": "gescher",
    "hours": []
  },
  {
    "name": "Zur Krone",
    "slug": "gescher-zur-krone",
    "type": "restaurant",
    "cuisine": "German",
    "description": "",
    "address": "Hauptstraße 39",
    "city": "Gescher",
    "postalCode": "48712",
    "latitude": 51.956274,
    "longitude": 7.006094,
    "priceTier": 2,
    "region": "gescher",
    "hours": [
      {
        "day": 0,
        "open": 720,
        "close": 840
      },
      {
        "day": 1,
        "open": 1080,
        "close": 1290
      }
    ]
  },
  {
    "name": "Ebbing",
    "slug": "gescher-ebbing",
    "type": "bakery",
    "cuisine": "",
    "description": "",
    "address": "",
    "city": "Gescher",
    "postalCode": "",
    "latitude": 51.960106,
    "longitude": 6.995365,
    "priceTier": 2,
    "region": "gescher",
    "hours": [
      {
        "day": 1,
        "open": 420,
        "close": 1200
      },
      {
        "day": 2,
        "open": 420,
        "close": 1200
      },
      {
        "day": 3,
        "open": 420,
        "close": 1200
      },
      {
        "day": 4,
        "open": 420,
        "close": 1200
      },
      {
        "day": 5,
        "open": 420,
        "close": 1200
      },
      {
        "day": 6,
        "open": 420,
        "close": 1080
      }
    ]
  },
  {
    "name": "Pizza Hood",
    "slug": "gescher-pizza-hood",
    "type": "restaurant",
    "cuisine": "Kebab, Pizza",
    "description": "",
    "address": "Borkener Damm 18",
    "city": "Gescher",
    "postalCode": "48712",
    "latitude": 51.954163,
    "longitude": 6.996126,
    "priceTier": 2,
    "region": "gescher",
    "hours": [
      {
        "day": 0,
        "open": 720,
        "close": 1320
      },
      {
        "day": 2,
        "open": 1020,
        "close": 1320
      },
      {
        "day": 3,
        "open": 1020,
        "close": 1320
      },
      {
        "day": 4,
        "open": 1020,
        "close": 1320
      },
      {
        "day": 5,
        "open": 960,
        "close": 1380
      },
      {
        "day": 6,
        "open": 960,
        "close": 1380
      }
    ]
  },
  {
    "name": "Damm",
    "slug": "gescher-damm",
    "type": "restaurant",
    "cuisine": "Regional",
    "description": "",
    "address": "Estern 6",
    "city": "Gescher",
    "postalCode": "48712",
    "latitude": 51.951394,
    "longitude": 6.974898,
    "priceTier": 2,
    "region": "gescher",
    "hours": []
  },
  {
    "name": "La Piccola Italia",
    "slug": "gescher-la-piccola-italia",
    "type": "restaurant",
    "cuisine": "Italian",
    "description": "",
    "address": "Hüpohl 29",
    "city": "Velen",
    "postalCode": "46342",
    "latitude": 51.888341,
    "longitude": 6.919044,
    "priceTier": 2,
    "region": "gescher",
    "hours": [
      {
        "day": 0,
        "open": 720,
        "close": 1320
      },
      {
        "day": 1,
        "open": 1020,
        "close": 1320
      },
      {
        "day": 2,
        "open": 1020,
        "close": 1320
      },
      {
        "day": 3,
        "open": 1020,
        "close": 1320
      },
      {
        "day": 4,
        "open": 1020,
        "close": 1320
      },
      {
        "day": 5,
        "open": 1020,
        "close": 0
      },
      {
        "day": 6,
        "open": 1020,
        "close": 0
      }
    ]
  },
  {
    "name": "Scharfe Kurve",
    "slug": "gescher-scharfe-kurve",
    "type": "restaurant",
    "cuisine": "",
    "description": "",
    "address": "Coesfelder Straße 18",
    "city": "Rosendahl",
    "postalCode": "48720",
    "latitude": 52.003236,
    "longitude": 7.129083,
    "priceTier": 2,
    "region": "gescher",
    "hours": [
      {
        "day": 0,
        "open": 1020,
        "close": 1380
      },
      {
        "day": 4,
        "open": 1020,
        "close": 1380
      },
      {
        "day": 5,
        "open": 1020,
        "close": 1380
      },
      {
        "day": 6,
        "open": 1020,
        "close": 1380
      }
    ]
  },
  {
    "name": "Mocca Brasserie",
    "slug": "gescher-mocca-brasserie",
    "type": "restaurant",
    "cuisine": "",
    "description": "",
    "address": "",
    "city": "Gescher",
    "postalCode": "",
    "latitude": 51.895149,
    "longitude": 6.986576,
    "priceTier": 2,
    "region": "gescher",
    "hours": []
  },
  {
    "name": "Gastro Brinkmanns Hof",
    "slug": "gescher-gastro-brinkmanns-hof",
    "type": "restaurant",
    "cuisine": "German, Spanish",
    "description": "",
    "address": "Harwick 52",
    "city": "Gescher",
    "postalCode": "48712",
    "latitude": 51.967628,
    "longitude": 7.007521,
    "priceTier": 2,
    "region": "gescher",
    "hours": []
  },
  {
    "name": "Hong Fu",
    "slug": "gescher-hong-fu",
    "type": "restaurant",
    "cuisine": "Asian",
    "description": "",
    "address": "Ahauser Damm 83",
    "city": "Gescher",
    "postalCode": "48712",
    "latitude": 51.972566,
    "longitude": 7.014902,
    "priceTier": 2,
    "region": "gescher",
    "hours": []
  },
  {
    "name": "Eiscafe Bäing",
    "slug": "gescher-eiscafe-baing",
    "type": "cafe",
    "cuisine": "Ice Cream, Cake",
    "description": "",
    "address": "Inselstraße 4",
    "city": "Gescher",
    "postalCode": "48712",
    "latitude": 51.955948,
    "longitude": 7.007334,
    "priceTier": 2,
    "region": "gescher",
    "hours": [
      {
        "day": 0,
        "open": 660,
        "close": 1260
      },
      {
        "day": 1,
        "open": 660,
        "close": 1260
      },
      {
        "day": 3,
        "open": 660,
        "close": 1260
      },
      {
        "day": 4,
        "open": 660,
        "close": 1260
      },
      {
        "day": 5,
        "open": 660,
        "close": 1260
      },
      {
        "day": 6,
        "open": 660,
        "close": 1260
      }
    ]
  },
  {
    "name": "Hundewicker Bahnhof",
    "slug": "gescher-hundewicker-bahnhof",
    "type": "restaurant",
    "cuisine": "German",
    "description": "",
    "address": "Eschlohn 25",
    "city": "Südlohn",
    "postalCode": "46354",
    "latitude": 51.966043,
    "longitude": 6.904333,
    "priceTier": 2,
    "region": "gescher",
    "hours": []
  },
  {
    "name": "Gallo",
    "slug": "gescher-gallo",
    "type": "restaurant",
    "cuisine": "Italian",
    "description": "",
    "address": "",
    "city": "Gescher",
    "postalCode": "",
    "latitude": 51.95588,
    "longitude": 7.003544,
    "priceTier": 2,
    "region": "gescher",
    "hours": []
  },
  {
    "name": "McKiernans Cafe",
    "slug": "gescher-mckiernans-cafe",
    "type": "cafe",
    "cuisine": "Irish, German",
    "description": "",
    "address": "Lindenstraße 1",
    "city": "Gescher",
    "postalCode": "48712",
    "latitude": 51.95633,
    "longitude": 7.002506,
    "priceTier": 2,
    "region": "gescher",
    "hours": [
      {
        "day": 0,
        "open": 540,
        "close": 1080
      },
      {
        "day": 3,
        "open": 540,
        "close": 1080
      },
      {
        "day": 4,
        "open": 540,
        "close": 1080
      },
      {
        "day": 5,
        "open": 540,
        "close": 1080
      },
      {
        "day": 6,
        "open": 540,
        "close": 1080
      }
    ]
  },
  {
    "name": "Eiscafe Venecia",
    "slug": "gescher-eiscafe-venecia",
    "type": "cafe",
    "cuisine": "Coffee",
    "description": "",
    "address": "Armlandstraße 14",
    "city": "Gescher",
    "postalCode": "48712",
    "latitude": 51.956267,
    "longitude": 7.003142,
    "priceTier": 2,
    "region": "gescher",
    "hours": []
  },
  {
    "name": "Späker",
    "slug": "gescher-spaker",
    "type": "bakery",
    "cuisine": "",
    "description": "",
    "address": "",
    "city": "Gescher",
    "postalCode": "",
    "latitude": 51.996331,
    "longitude": 6.928753,
    "priceTier": 2,
    "region": "gescher",
    "hours": [
      {
        "day": 1,
        "open": 480,
        "close": 1140
      },
      {
        "day": 2,
        "open": 480,
        "close": 1140
      },
      {
        "day": 3,
        "open": 480,
        "close": 1140
      },
      {
        "day": 4,
        "open": 480,
        "close": 1140
      },
      {
        "day": 5,
        "open": 480,
        "close": 1140
      },
      {
        "day": 6,
        "open": 480,
        "close": 1080
      }
    ]
  },
  {
    "name": "Westfalenstube",
    "slug": "gescher-westfalenstube",
    "type": "restaurant",
    "cuisine": "",
    "description": "",
    "address": "Westfalenring 36",
    "city": "Gescher",
    "postalCode": "48712",
    "latitude": 51.951635,
    "longitude": 6.996926,
    "priceTier": 2,
    "region": "gescher",
    "hours": []
  },
  {
    "name": "Golf- und Landklub",
    "slug": "gescher-golf-und-landklub",
    "type": "restaurant",
    "cuisine": "German",
    "description": "",
    "address": "Stevede 8a",
    "city": "Coesfeld",
    "postalCode": "48653",
    "latitude": 51.911936,
    "longitude": 7.10907,
    "priceTier": 2,
    "region": "gescher",
    "hours": []
  },
  {
    "name": "La Rosa",
    "slug": "gescher-la-rosa",
    "type": "restaurant",
    "cuisine": "Italian, Pizza",
    "description": "",
    "address": "",
    "city": "Gescher",
    "postalCode": "",
    "latitude": 51.990907,
    "longitude": 6.917904,
    "priceTier": 2,
    "region": "gescher",
    "hours": []
  },
  {
    "name": "China Restaurant Hong Kong",
    "slug": "gescher-china-restaurant-hong-kong",
    "type": "restaurant",
    "cuisine": "Chinese",
    "description": "",
    "address": "Eschstraße 35",
    "city": "Stadtlohn",
    "postalCode": "48703",
    "latitude": 51.989608,
    "longitude": 6.914752,
    "priceTier": 2,
    "region": "gescher",
    "hours": []
  },
  {
    "name": "Hof Menker",
    "slug": "gescher-hof-menker",
    "type": "farm",
    "cuisine": "",
    "description": "",
    "address": "",
    "city": "Gescher",
    "postalCode": "",
    "latitude": 51.947637,
    "longitude": 7.066331,
    "priceTier": 2,
    "region": "gescher",
    "hours": []
  },
  {
    "name": "Hosselmann",
    "slug": "gescher-hosselmann",
    "type": "cafe",
    "cuisine": "Coffee",
    "description": "",
    "address": "Legdener Straße 2",
    "city": "Rosendahl",
    "postalCode": "48720",
    "latitude": 52.005838,
    "longitude": 7.128359,
    "priceTier": 2,
    "region": "gescher",
    "hours": [
      {
        "day": 0,
        "open": 420,
        "close": 1020
      },
      {
        "day": 1,
        "open": 360,
        "close": 1080
      },
      {
        "day": 2,
        "open": 360,
        "close": 1080
      },
      {
        "day": 3,
        "open": 360,
        "close": 1080
      },
      {
        "day": 4,
        "open": 360,
        "close": 1080
      },
      {
        "day": 5,
        "open": 360,
        "close": 1080
      },
      {
        "day": 6,
        "open": 360,
        "close": 1080
      }
    ]
  }
]
