/**
 * Real places around Wuppertal, imported from OpenStreetMap.
 *
 * Generated by `buddy import:places --region wuppertal`. Do not edit by
 * hand: the curated listings live in `businesses.ts`, which is where a
 * correction belongs.
 *
 * These businesses have agreed to nothing. They are listed and searchable and
 * that is all: no reviews, no orders, and a claim form that leads with taking
 * the listing down. Data from OpenStreetMap contributors, ODbL.
 */

import type { SeedBusiness } from './businesses'

export const OSM_LISTINGS_WUPPERTAL: SeedBusiness[] = [
  {
    "name": "Cafe Extrablatt",
    "slug": "wuppertal-cafe-extrablatt",
    "type": "cafe",
    "cuisine": "Coffee Shop",
    "description": "",
    "address": "Grabenstraße 5",
    "city": "Wuppertal",
    "postalCode": "42103",
    "latitude": 51.258534,
    "longitude": 7.147602,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Kleine Schweiz",
    "slug": "wuppertal-kleine-schweiz",
    "type": "restaurant",
    "cuisine": "",
    "description": "",
    "address": "Wimmersberger Straße 125",
    "city": "Velbert",
    "postalCode": "42553",
    "latitude": 51.306277,
    "longitude": 7.046392,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Gut Hahn",
    "slug": "wuppertal-gut-hahn",
    "type": "restaurant",
    "cuisine": "International",
    "description": "",
    "address": "Rheinische Straße 13-15",
    "city": "Haan",
    "postalCode": "42781",
    "latitude": 51.205351,
    "longitude": 7.028668,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 0,
        "open": 720,
        "close": 1260
      },
      {
        "day": 3,
        "open": 1020,
        "close": 1380
      },
      {
        "day": 4,
        "open": 1020,
        "close": 1380
      },
      {
        "day": 5,
        "open": 1020,
        "close": 1380
      },
      {
        "day": 6,
        "open": 720,
        "close": 1380
      }
    ]
  },
  {
    "name": "Haus Sondermann",
    "slug": "wuppertal-haus-sondermann",
    "type": "restaurant",
    "cuisine": "Regional",
    "description": "",
    "address": "",
    "city": "Wuppertal",
    "postalCode": "",
    "latitude": 51.303706,
    "longitude": 7.121274,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Haaner Hof",
    "slug": "wuppertal-haaner-hof",
    "type": "restaurant",
    "cuisine": "",
    "description": "",
    "address": "Elberfelder Straße 239",
    "city": "Haan",
    "postalCode": "42781",
    "latitude": 51.214532,
    "longitude": 7.037783,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 0,
        "open": 720,
        "close": 1350
      },
      {
        "day": 4,
        "open": 1050,
        "close": 1350
      }
    ]
  },
  {
    "name": "Königshöhe",
    "slug": "wuppertal-konigshohe",
    "type": "restaurant",
    "cuisine": "Italian",
    "description": "",
    "address": "Köhlweg 1",
    "city": "Wuppertal",
    "postalCode": "42117",
    "latitude": 51.236922,
    "longitude": 7.12554,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Akropolis",
    "slug": "wuppertal-akropolis",
    "type": "restaurant",
    "cuisine": "Greek, International",
    "description": "",
    "address": "",
    "city": "Wuppertal",
    "postalCode": "",
    "latitude": 51.310399,
    "longitude": 7.088643,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Mykonos",
    "slug": "wuppertal-mykonos",
    "type": "restaurant",
    "cuisine": "Greek",
    "description": "",
    "address": "Zur Loev 10",
    "city": "Wülfrath",
    "postalCode": "42489",
    "latitude": 51.282869,
    "longitude": 7.030424,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 2,
        "open": 1020,
        "close": 1350
      },
      {
        "day": 3,
        "open": 1020,
        "close": 1350
      },
      {
        "day": 4,
        "open": 1020,
        "close": 1350
      },
      {
        "day": 5,
        "open": 1020,
        "close": 1350
      }
    ]
  },
  {
    "name": "Richrather Mühle",
    "slug": "wuppertal-richrather-muhle",
    "type": "bakery",
    "cuisine": "",
    "description": "",
    "address": "Ellenbeek 4",
    "city": "Wülfrath",
    "postalCode": "42489",
    "latitude": 51.284769,
    "longitude": 7.049407,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Hardt-Stübchen",
    "slug": "wuppertal-hardt-stubchen",
    "type": "restaurant",
    "cuisine": "Regional, German",
    "description": "",
    "address": "Elisenhöhe 4",
    "city": "Wuppertal",
    "postalCode": "42107",
    "latitude": 51.26078,
    "longitude": 7.161741,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "KYTO Coffee Wuppertal",
    "slug": "wuppertal-kyto-coffee-wuppertal",
    "type": "cafe",
    "cuisine": "Coffee",
    "description": "",
    "address": "Neumarkt 5-7",
    "city": "Wuppertal",
    "postalCode": "42103",
    "latitude": 51.25863,
    "longitude": 7.147006,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 0,
        "open": 660,
        "close": 1020
      },
      {
        "day": 1,
        "open": 480,
        "close": 1080
      },
      {
        "day": 2,
        "open": 480,
        "close": 1080
      },
      {
        "day": 3,
        "open": 480,
        "close": 1080
      },
      {
        "day": 4,
        "open": 480,
        "close": 1080
      },
      {
        "day": 5,
        "open": 480,
        "close": 1080
      },
      {
        "day": 6,
        "open": 600,
        "close": 1140
      }
    ]
  },
  {
    "name": "Cafe Podzelny",
    "slug": "wuppertal-cafe-podzelny",
    "type": "cafe",
    "cuisine": "Coffee",
    "description": "",
    "address": "",
    "city": "Wuppertal",
    "postalCode": "",
    "latitude": 51.214698,
    "longitude": 7.145454,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Laurenz",
    "slug": "wuppertal-laurenz",
    "type": "restaurant",
    "cuisine": "",
    "description": "",
    "address": "Laurentiusplatz 1",
    "city": "Wuppertal",
    "postalCode": "42103",
    "latitude": 51.256121,
    "longitude": 7.13942,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Haus Mees",
    "slug": "wuppertal-haus-mees",
    "type": "restaurant",
    "cuisine": "",
    "description": "",
    "address": "",
    "city": "Wuppertal",
    "postalCode": "",
    "latitude": 51.215004,
    "longitude": 7.146509,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Haus Zillertal",
    "slug": "wuppertal-haus-zillertal",
    "type": "restaurant",
    "cuisine": "German",
    "description": "",
    "address": "Zillertal 1",
    "city": "Wuppertal",
    "postalCode": "42349",
    "latitude": 51.211412,
    "longitude": 7.165173,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Der Grund",
    "slug": "wuppertal-der-grund",
    "type": "restaurant",
    "cuisine": "German",
    "description": "",
    "address": "Grund 41",
    "city": "Wuppertal",
    "postalCode": "",
    "latitude": 51.205427,
    "longitude": 7.185058,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 0,
        "open": 1080,
        "close": 1260
      },
      {
        "day": 3,
        "open": 1080,
        "close": 1260
      },
      {
        "day": 4,
        "open": 1080,
        "close": 1260
      },
      {
        "day": 5,
        "open": 1080,
        "close": 1260
      },
      {
        "day": 6,
        "open": 1080,
        "close": 1260
      }
    ]
  },
  {
    "name": "Fiorello",
    "slug": "wuppertal-fiorello",
    "type": "restaurant",
    "cuisine": "Italian",
    "description": "",
    "address": "Wilhelmring 125",
    "city": "Wuppertal",
    "postalCode": "42349",
    "latitude": 51.222337,
    "longitude": 7.150886,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Milia's Coffee",
    "slug": "wuppertal-milia-s-coffee",
    "type": "cafe",
    "cuisine": "Coffee Shop",
    "description": "",
    "address": "Kirchstraße 10",
    "city": "Wuppertal",
    "postalCode": "42103",
    "latitude": 51.256789,
    "longitude": 7.147217,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 0,
        "open": 630,
        "close": 1140
      },
      {
        "day": 1,
        "open": 420,
        "close": 1200
      },
      {
        "day": 2,
        "open": 420,
        "close": 1200
      },
      {
        "day": 3,
        "open": 420,
        "close": 1200
      },
      {
        "day": 4,
        "open": 420,
        "close": 1200
      },
      {
        "day": 5,
        "open": 420,
        "close": 1200
      },
      {
        "day": 6,
        "open": 480,
        "close": 1140
      }
    ]
  },
  {
    "name": "SOMA Rest-o-Bar",
    "slug": "wuppertal-soma-rest-o-bar",
    "type": "restaurant",
    "cuisine": "Tapas",
    "description": "",
    "address": "Herzogstraße 42",
    "city": "Wuppertal",
    "postalCode": "42103",
    "latitude": 51.257126,
    "longitude": 7.142574,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Il Tarantino",
    "slug": "wuppertal-il-tarantino",
    "type": "restaurant",
    "cuisine": "Italian",
    "description": "",
    "address": "Alexanderstraße 18",
    "city": "Wuppertal",
    "postalCode": "42103",
    "latitude": 51.25525,
    "longitude": 7.143767,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Ganesh",
    "slug": "wuppertal-ganesh",
    "type": "restaurant",
    "cuisine": "Indian",
    "description": "",
    "address": "Wülfrather Straße 17",
    "city": "Wuppertal",
    "postalCode": "42105",
    "latitude": 51.261672,
    "longitude": 7.136426,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 0,
        "open": 1050,
        "close": 1380
      },
      {
        "day": 1,
        "open": 1050,
        "close": 1380
      },
      {
        "day": 2,
        "open": 1050,
        "close": 1380
      },
      {
        "day": 3,
        "open": 1050,
        "close": 1380
      },
      {
        "day": 4,
        "open": 1050,
        "close": 1380
      },
      {
        "day": 5,
        "open": 1050,
        "close": 1380
      },
      {
        "day": 6,
        "open": 1050,
        "close": 1380
      }
    ]
  },
  {
    "name": "Cay Ocegi",
    "slug": "wuppertal-cay-ocegi",
    "type": "cafe",
    "cuisine": "Coffee",
    "description": "",
    "address": "",
    "city": "Wuppertal",
    "postalCode": "",
    "latitude": 51.22952,
    "longitude": 7.064686,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Mezra",
    "slug": "wuppertal-mezra",
    "type": "bakery",
    "cuisine": "",
    "description": "",
    "address": "",
    "city": "Wuppertal",
    "postalCode": "",
    "latitude": 51.23123,
    "longitude": 7.070029,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Havanna",
    "slug": "wuppertal-havanna",
    "type": "restaurant",
    "cuisine": "",
    "description": "",
    "address": "Vohwinkeler Straße 25",
    "city": "Wuppertal",
    "postalCode": "42329",
    "latitude": 51.230024,
    "longitude": 7.067698,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Bäckerei Steinbrink",
    "slug": "wuppertal-backerei-steinbrink",
    "type": "cafe",
    "cuisine": "Coffee",
    "description": "",
    "address": "Kaiserstraße 11",
    "city": "Wuppertal",
    "postalCode": "42329",
    "latitude": 51.231673,
    "longitude": 7.07115,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 0,
        "open": 420,
        "close": 720
      },
      {
        "day": 1,
        "open": 360,
        "close": 1080
      },
      {
        "day": 2,
        "open": 360,
        "close": 1080
      },
      {
        "day": 3,
        "open": 360,
        "close": 1080
      },
      {
        "day": 4,
        "open": 360,
        "close": 1080
      },
      {
        "day": 5,
        "open": 360,
        "close": 1080
      },
      {
        "day": 6,
        "open": 360,
        "close": 840
      }
    ]
  },
  {
    "name": "Café Bistro Hammerstein",
    "slug": "wuppertal-cafe-bistro-hammerstein",
    "type": "cafe",
    "cuisine": "Coffee",
    "description": "",
    "address": "Kaiserstraße 184",
    "city": "Wuppertal",
    "postalCode": "42329",
    "latitude": 51.235737,
    "longitude": 7.087068,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Eiscafe Mandolino",
    "slug": "wuppertal-eiscafe-mandolino",
    "type": "cafe",
    "cuisine": "Coffee",
    "description": "",
    "address": "",
    "city": "Wuppertal",
    "postalCode": "",
    "latitude": 51.256118,
    "longitude": 7.140053,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Cafe Engel",
    "slug": "wuppertal-cafe-engel",
    "type": "restaurant",
    "cuisine": "",
    "description": "",
    "address": "Friedrich-Ebert-Straße 13",
    "city": "Wuppertal",
    "postalCode": "42103",
    "latitude": 51.256167,
    "longitude": 7.140196,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Juce Breakfast all day",
    "slug": "wuppertal-juce-breakfast-all-day",
    "type": "restaurant",
    "cuisine": "Breakfast, Indian",
    "description": "",
    "address": "Friedrich-Ebert-Straße 41",
    "city": "Wuppertal",
    "postalCode": "42103",
    "latitude": 51.255304,
    "longitude": 7.13765,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "La Bottega 46",
    "slug": "wuppertal-la-bottega-46",
    "type": "restaurant",
    "cuisine": "Italian",
    "description": "",
    "address": "Alsenstraße 23",
    "city": "Wuppertal",
    "postalCode": "42103",
    "latitude": 51.252292,
    "longitude": 7.138006,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Santorini Grill",
    "slug": "wuppertal-santorini-grill",
    "type": "restaurant",
    "cuisine": "Greek",
    "description": "",
    "address": "Wülfrather Straße 1",
    "city": "Velbert",
    "postalCode": "42553",
    "latitude": 51.312767,
    "longitude": 7.06673,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 0,
        "open": 690,
        "close": 1320
      },
      {
        "day": 2,
        "open": 690,
        "close": 1320
      },
      {
        "day": 3,
        "open": 690,
        "close": 1320
      },
      {
        "day": 4,
        "open": 690,
        "close": 1320
      },
      {
        "day": 5,
        "open": 690,
        "close": 1320
      },
      {
        "day": 6,
        "open": 690,
        "close": 1320
      }
    ]
  },
  {
    "name": "Kulisse",
    "slug": "wuppertal-kulisse",
    "type": "restaurant",
    "cuisine": "",
    "description": "",
    "address": "",
    "city": "Wuppertal",
    "postalCode": "",
    "latitude": 51.235642,
    "longitude": 7.083115,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Windrather Hof",
    "slug": "wuppertal-windrather-hof",
    "type": "restaurant",
    "cuisine": "",
    "description": "",
    "address": "",
    "city": "Wuppertal",
    "postalCode": "",
    "latitude": 51.311698,
    "longitude": 7.147999,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Taormina",
    "slug": "wuppertal-taormina",
    "type": "restaurant",
    "cuisine": "Italian",
    "description": "",
    "address": "Südstraße 26",
    "city": "Wuppertal",
    "postalCode": "42103",
    "latitude": 51.252277,
    "longitude": 7.140407,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Croatien",
    "slug": "wuppertal-croatien",
    "type": "restaurant",
    "cuisine": "",
    "description": "",
    "address": "Südstraße 10",
    "city": "Wuppertal",
    "postalCode": "42103",
    "latitude": 51.252913,
    "longitude": 7.139867,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Schlosscafé Lüntenbeck",
    "slug": "wuppertal-schlosscafe-luntenbeck",
    "type": "restaurant",
    "cuisine": "International",
    "description": "",
    "address": "Lüntenbeck 1",
    "city": "Wuppertal",
    "postalCode": "42327",
    "latitude": 51.250981,
    "longitude": 7.083703,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Steinbrink",
    "slug": "wuppertal-steinbrink",
    "type": "bakery",
    "cuisine": "",
    "description": "",
    "address": "Heckinghauser Straße 170",
    "city": "Wuppertal",
    "postalCode": "42289",
    "latitude": 51.271062,
    "longitude": 7.222087,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 0,
        "open": 420,
        "close": 900
      },
      {
        "day": 1,
        "open": 360,
        "close": 1080
      },
      {
        "day": 2,
        "open": 360,
        "close": 1080
      },
      {
        "day": 3,
        "open": 360,
        "close": 1080
      },
      {
        "day": 4,
        "open": 360,
        "close": 1080
      },
      {
        "day": 5,
        "open": 360,
        "close": 1080
      },
      {
        "day": 6,
        "open": 360,
        "close": 900
      }
    ]
  },
  {
    "name": "Pizzeria Picco Bello",
    "slug": "wuppertal-pizzeria-picco-bello",
    "type": "restaurant",
    "cuisine": "Italian",
    "description": "",
    "address": "",
    "city": "Wuppertal",
    "postalCode": "",
    "latitude": 51.234772,
    "longitude": 7.081915,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Alaturka",
    "slug": "wuppertal-alaturka",
    "type": "restaurant",
    "cuisine": "",
    "description": "",
    "address": "Luisenstraße 63",
    "city": "Wuppertal",
    "postalCode": "42103",
    "latitude": 51.256435,
    "longitude": 7.137798,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Ristorante Da Pino",
    "slug": "wuppertal-ristorante-da-pino",
    "type": "restaurant",
    "cuisine": "Pizza, Italian",
    "description": "",
    "address": "Altmarkt 3",
    "city": "Schwelm",
    "postalCode": "58332",
    "latitude": 51.283597,
    "longitude": 7.292534,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Eisenwerkschänke",
    "slug": "wuppertal-eisenwerkschanke",
    "type": "restaurant",
    "cuisine": "Steak House",
    "description": "",
    "address": "Loher Straße 5",
    "city": "Schwelm",
    "postalCode": "58332",
    "latitude": 51.291821,
    "longitude": 7.294255,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 0,
        "open": 1080,
        "close": 0
      },
      {
        "day": 3,
        "open": 1080,
        "close": 0
      },
      {
        "day": 4,
        "open": 1080,
        "close": 0
      },
      {
        "day": 5,
        "open": 1080,
        "close": 0
      },
      {
        "day": 6,
        "open": 1080,
        "close": 0
      }
    ]
  },
  {
    "name": "Devrans",
    "slug": "wuppertal-devrans",
    "type": "restaurant",
    "cuisine": "Turkish",
    "description": "",
    "address": "",
    "city": "Wuppertal",
    "postalCode": "",
    "latitude": 51.28863,
    "longitude": 7.296292,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Bäckerei Poguntke",
    "slug": "wuppertal-backerei-poguntke",
    "type": "bakery",
    "cuisine": "",
    "description": "",
    "address": "",
    "city": "Wuppertal",
    "postalCode": "",
    "latitude": 51.26235,
    "longitude": 7.18557,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Cafeteria im Amtsgericht",
    "slug": "wuppertal-cafeteria-im-amtsgericht",
    "type": "restaurant",
    "cuisine": "",
    "description": "",
    "address": "",
    "city": "Wuppertal",
    "postalCode": "",
    "latitude": 51.257161,
    "longitude": 7.161797,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Sonnengruß",
    "slug": "wuppertal-sonnengru",
    "type": "cafe",
    "cuisine": "Coffee",
    "description": "",
    "address": "",
    "city": "Wuppertal",
    "postalCode": "",
    "latitude": 51.243034,
    "longitude": 7.1551,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Elfriedenhöhe",
    "slug": "wuppertal-elfriedenhohe",
    "type": "restaurant",
    "cuisine": "German",
    "description": "",
    "address": "Haarhauser Bruch 1",
    "city": "Wuppertal",
    "postalCode": "42279",
    "latitude": 51.296853,
    "longitude": 7.222279,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 0,
        "open": 690,
        "close": 1320
      }
    ]
  },
  {
    "name": "Trassenstube",
    "slug": "wuppertal-trassenstube",
    "type": "restaurant",
    "cuisine": "German",
    "description": "",
    "address": "",
    "city": "Wuppertal",
    "postalCode": "",
    "latitude": 51.252688,
    "longitude": 7.09885,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Cafe Du Congo",
    "slug": "wuppertal-cafe-du-congo",
    "type": "restaurant",
    "cuisine": "",
    "description": "",
    "address": "Luisenstraße 118",
    "city": "Wuppertal",
    "postalCode": "42103",
    "latitude": 51.255888,
    "longitude": 7.135883,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 0,
        "open": 720,
        "close": 1320
      },
      {
        "day": 2,
        "open": 1020,
        "close": 1320
      },
      {
        "day": 3,
        "open": 1020,
        "close": 1320
      },
      {
        "day": 4,
        "open": 1020,
        "close": 1320
      },
      {
        "day": 5,
        "open": 1020,
        "close": 1320
      },
      {
        "day": 6,
        "open": 720,
        "close": 1320
      }
    ]
  },
  {
    "name": "Brusco",
    "slug": "wuppertal-brusco",
    "type": "restaurant",
    "cuisine": "Greek",
    "description": "",
    "address": "",
    "city": "Wuppertal",
    "postalCode": "",
    "latitude": 51.213318,
    "longitude": 7.035471,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 0,
        "open": 690,
        "close": 1380
      }
    ]
  },
  {
    "name": "Essen'z Restaurant am Jägerhaus",
    "slug": "wuppertal-essen-z-restaurant-am-jagerhaus",
    "type": "restaurant",
    "cuisine": "Fine Dining",
    "description": "",
    "address": "Jägerhaus 87",
    "city": "Wuppertal",
    "postalCode": "42287",
    "latitude": 51.238846,
    "longitude": 7.235547,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Nonna di Mia",
    "slug": "wuppertal-nonna-di-mia",
    "type": "restaurant",
    "cuisine": "",
    "description": "",
    "address": "",
    "city": "Wuppertal",
    "postalCode": "42103",
    "latitude": 51.257028,
    "longitude": 7.142185,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Katzengold",
    "slug": "wuppertal-katzengold",
    "type": "restaurant",
    "cuisine": "",
    "description": "",
    "address": "Untergrünewalder Straße 3",
    "city": "Wuppertal",
    "postalCode": "42103",
    "latitude": 51.25593,
    "longitude": 7.136289,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Ristorante Paciello",
    "slug": "wuppertal-ristorante-paciello",
    "type": "restaurant",
    "cuisine": "Italian, Regional",
    "description": "",
    "address": "",
    "city": "Wuppertal",
    "postalCode": "",
    "latitude": 51.312612,
    "longitude": 7.08846,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 1,
        "open": 1020,
        "close": 1350
      },
      {
        "day": 2,
        "open": 1020,
        "close": 1350
      },
      {
        "day": 3,
        "open": 1020,
        "close": 1350
      },
      {
        "day": 4,
        "open": 1020,
        "close": 1350
      },
      {
        "day": 5,
        "open": 1020,
        "close": 1350
      },
      {
        "day": 6,
        "open": 1020,
        "close": 1350
      }
    ]
  },
  {
    "name": "Café Moritz",
    "slug": "wuppertal-cafe-moritz",
    "type": "restaurant",
    "cuisine": "",
    "description": "",
    "address": "Höhne 22",
    "city": "Wuppertal",
    "postalCode": "42275",
    "latitude": 51.269962,
    "longitude": 7.199906,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 1,
        "open": 540,
        "close": 1320
      },
      {
        "day": 2,
        "open": 540,
        "close": 1320
      },
      {
        "day": 3,
        "open": 540,
        "close": 1320
      },
      {
        "day": 4,
        "open": 540,
        "close": 1320
      },
      {
        "day": 5,
        "open": 540,
        "close": 1320
      }
    ]
  },
  {
    "name": "Casa Pedro",
    "slug": "wuppertal-casa-pedro",
    "type": "restaurant",
    "cuisine": "Spanish",
    "description": "",
    "address": "",
    "city": "Wuppertal",
    "postalCode": "",
    "latitude": 51.208161,
    "longitude": 7.071033,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 0,
        "open": 1080,
        "close": 1440
      },
      {
        "day": 1,
        "open": 1080,
        "close": 1440
      },
      {
        "day": 2,
        "open": 1080,
        "close": 1440
      },
      {
        "day": 3,
        "open": 1080,
        "close": 1440
      },
      {
        "day": 4,
        "open": 1080,
        "close": 1440
      },
      {
        "day": 5,
        "open": 1080,
        "close": 1440
      },
      {
        "day": 6,
        "open": 1080,
        "close": 1440
      }
    ]
  },
  {
    "name": "Don Camillo & Peppone",
    "slug": "wuppertal-don-camillo-and-peppone",
    "type": "restaurant",
    "cuisine": "Italian",
    "description": "",
    "address": "Friedrich-Ebert-Straße 16",
    "city": "Wuppertal",
    "postalCode": "42103",
    "latitude": 51.256433,
    "longitude": 7.140389,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 0,
        "open": 780,
        "close": 1380
      },
      {
        "day": 1,
        "open": 660,
        "close": 1380
      },
      {
        "day": 2,
        "open": 660,
        "close": 1380
      },
      {
        "day": 3,
        "open": 660,
        "close": 1380
      },
      {
        "day": 4,
        "open": 660,
        "close": 1380
      },
      {
        "day": 5,
        "open": 660,
        "close": 1380
      },
      {
        "day": 6,
        "open": 660,
        "close": 1380
      }
    ]
  },
  {
    "name": "Amalfi",
    "slug": "wuppertal-amalfi",
    "type": "restaurant",
    "cuisine": "Italian",
    "description": "",
    "address": "Laurentiusplatz",
    "city": "Wuppertal",
    "postalCode": "42103",
    "latitude": 51.256775,
    "longitude": 7.140069,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Scarpati",
    "slug": "wuppertal-scarpati",
    "type": "restaurant",
    "cuisine": "Italian",
    "description": "",
    "address": "Scheffelstraße 41",
    "city": "Wuppertal",
    "postalCode": "42327",
    "latitude": 51.238962,
    "longitude": 7.084979,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Schliepershäuschen",
    "slug": "wuppertal-schliepershauschen",
    "type": "restaurant",
    "cuisine": "",
    "description": "",
    "address": "Düsseldorfer Straße 115",
    "city": "Wuppertal",
    "postalCode": "42115",
    "latitude": 51.25583,
    "longitude": 7.091734,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Shiraz",
    "slug": "wuppertal-shiraz",
    "type": "restaurant",
    "cuisine": "Polish",
    "description": "",
    "address": "Wittener Straße 288",
    "city": "Wuppertal",
    "postalCode": "42279",
    "latitude": 51.302776,
    "longitude": 7.251939,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 0,
        "open": 780,
        "close": 1320
      },
      {
        "day": 3,
        "open": 1050,
        "close": 1340
      },
      {
        "day": 4,
        "open": 1050,
        "close": 1340
      },
      {
        "day": 5,
        "open": 1050,
        "close": 1340
      },
      {
        "day": 6,
        "open": 1050,
        "close": 1340
      }
    ]
  },
  {
    "name": "Kaffeehaus",
    "slug": "wuppertal-kaffeehaus",
    "type": "cafe",
    "cuisine": "Coffee",
    "description": "",
    "address": "Gräfrather Markt 7",
    "city": "Solingen",
    "postalCode": "42653",
    "latitude": 51.208988,
    "longitude": 7.071418,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Rainbow Park Restaurant",
    "slug": "wuppertal-rainbow-park-restaurant",
    "type": "restaurant",
    "cuisine": "",
    "description": "",
    "address": "",
    "city": "Wuppertal",
    "postalCode": "",
    "latitude": 51.291892,
    "longitude": 7.170983,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Bäcker Schüren",
    "slug": "wuppertal-backer-schuren",
    "type": "bakery",
    "cuisine": "",
    "description": "",
    "address": "Bahnstraße 10",
    "city": "Wuppertal",
    "postalCode": "42327",
    "latitude": 51.23198,
    "longitude": 7.07057,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 1,
        "open": 420,
        "close": 1080
      },
      {
        "day": 2,
        "open": 420,
        "close": 1080
      },
      {
        "day": 3,
        "open": 420,
        "close": 1080
      },
      {
        "day": 4,
        "open": 420,
        "close": 1080
      },
      {
        "day": 5,
        "open": 420,
        "close": 1080
      },
      {
        "day": 6,
        "open": 420,
        "close": 780
      }
    ]
  },
  {
    "name": "Il Ghiotto Osteria",
    "slug": "wuppertal-il-ghiotto-osteria",
    "type": "restaurant",
    "cuisine": "International",
    "description": "",
    "address": "Friedrich-Ebert-Straße 88",
    "city": "Wuppertal",
    "postalCode": "42103",
    "latitude": 51.253972,
    "longitude": 7.13356,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 0,
        "open": 690,
        "close": 1320
      },
      {
        "day": 2,
        "open": 690,
        "close": 1320
      },
      {
        "day": 3,
        "open": 690,
        "close": 1320
      },
      {
        "day": 4,
        "open": 690,
        "close": 1320
      },
      {
        "day": 5,
        "open": 690,
        "close": 1350
      },
      {
        "day": 6,
        "open": 690,
        "close": 1350
      }
    ]
  },
  {
    "name": "Incontro",
    "slug": "wuppertal-incontro",
    "type": "restaurant",
    "cuisine": "",
    "description": "",
    "address": "Friedrich-Ebert-Straße 88",
    "city": "Wuppertal",
    "postalCode": "42103",
    "latitude": 51.25418,
    "longitude": 7.134206,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Haveli",
    "slug": "wuppertal-haveli",
    "type": "restaurant",
    "cuisine": "Indian",
    "description": "",
    "address": "Bankstraße 4",
    "city": "Wuppertal",
    "postalCode": "42103",
    "latitude": 51.256993,
    "longitude": 7.143529,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 0,
        "open": 720,
        "close": 1320
      }
    ]
  },
  {
    "name": "The Loft",
    "slug": "wuppertal-the-loft",
    "type": "restaurant",
    "cuisine": "Burger, Mediterranean",
    "description": "",
    "address": "Friedrich-Ebert-Straße 14",
    "city": "Wuppertal",
    "postalCode": "42103",
    "latitude": 51.256482,
    "longitude": 7.140518,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 0,
        "open": 600,
        "close": 1380
      },
      {
        "day": 1,
        "open": 600,
        "close": 1380
      },
      {
        "day": 2,
        "open": 600,
        "close": 1380
      },
      {
        "day": 3,
        "open": 600,
        "close": 1380
      },
      {
        "day": 4,
        "open": 600,
        "close": 1380
      },
      {
        "day": 5,
        "open": 600,
        "close": 1380
      },
      {
        "day": 6,
        "open": 600,
        "close": 1380
      }
    ]
  },
  {
    "name": "Landgasthof Sondermann's Zur Bergeshöh",
    "slug": "wuppertal-landgasthof-sondermann-s-zur-bergeshoh",
    "type": "restaurant",
    "cuisine": "Regional",
    "description": "",
    "address": "Höhenweg 89",
    "city": "Schwelm",
    "postalCode": "58332",
    "latitude": 51.303145,
    "longitude": 7.290837,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Bergischer Hof",
    "slug": "wuppertal-bergischer-hof",
    "type": "restaurant",
    "cuisine": "Balkan",
    "description": "",
    "address": "Marktstraße 41",
    "city": "Wuppertal",
    "postalCode": "42369",
    "latitude": 51.226578,
    "longitude": 7.19827,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Tai Lake",
    "slug": "wuppertal-tai-lake",
    "type": "restaurant",
    "cuisine": "Chinese",
    "description": "",
    "address": "Friedrich-Ebert-Straße 131",
    "city": "Wuppertal",
    "postalCode": "42117",
    "latitude": 51.249893,
    "longitude": 7.129753,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Café Norrenberg",
    "slug": "wuppertal-cafe-norrenberg",
    "type": "cafe",
    "cuisine": "Coffee",
    "description": "",
    "address": "Theodor-Fontane-Straße 50",
    "city": "Wuppertal",
    "postalCode": "42289",
    "latitude": 51.268045,
    "longitude": 7.228733,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Vereinsheim KGV Springen e.V.",
    "slug": "wuppertal-vereinsheim-kgv-springen-e-v",
    "type": "restaurant",
    "cuisine": "",
    "description": "",
    "address": "Obere Lichtenplatzer Straße 160",
    "city": "Wuppertal",
    "postalCode": "42287",
    "latitude": 51.259445,
    "longitude": 7.190936,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "central",
    "slug": "wuppertal-central",
    "type": "restaurant",
    "cuisine": "",
    "description": "",
    "address": "",
    "city": "Wuppertal",
    "postalCode": "",
    "latitude": 51.227213,
    "longitude": 7.197396,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 0,
        "open": 600,
        "close": 840
      },
      {
        "day": 6,
        "open": 600,
        "close": 1440
      }
    ]
  },
  {
    "name": "Schönebeck",
    "slug": "wuppertal-schonebeck",
    "type": "bakery",
    "cuisine": "",
    "description": "",
    "address": "Schönebecker Straße 45",
    "city": "Wuppertal",
    "postalCode": "42283",
    "latitude": 51.27322,
    "longitude": 7.178755,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 0,
        "open": 480,
        "close": 720
      },
      {
        "day": 1,
        "open": 300,
        "close": 900
      },
      {
        "day": 2,
        "open": 300,
        "close": 900
      },
      {
        "day": 3,
        "open": 300,
        "close": 900
      },
      {
        "day": 4,
        "open": 300,
        "close": 900
      },
      {
        "day": 5,
        "open": 300,
        "close": 900
      },
      {
        "day": 6,
        "open": 300,
        "close": 720
      }
    ]
  },
  {
    "name": "Hopfengarten",
    "slug": "wuppertal-hopfengarten",
    "type": "restaurant",
    "cuisine": "",
    "description": "",
    "address": "",
    "city": "Wuppertal",
    "postalCode": "",
    "latitude": 51.289332,
    "longitude": 7.293447,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Caffè³",
    "slug": "wuppertal-caffe",
    "type": "cafe",
    "cuisine": "Coffee",
    "description": "",
    "address": "",
    "city": "Wuppertal",
    "postalCode": "",
    "latitude": 51.284773,
    "longitude": 7.294882,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "W. Behmer",
    "slug": "wuppertal-w-behmer",
    "type": "bakery",
    "cuisine": "",
    "description": "",
    "address": "",
    "city": "Wuppertal",
    "postalCode": "",
    "latitude": 51.282571,
    "longitude": 7.215011,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Alt und neu",
    "slug": "wuppertal-alt-und-neu",
    "type": "restaurant",
    "cuisine": "German",
    "description": "",
    "address": "Holthauser Straße 126",
    "city": "Wuppertal",
    "postalCode": "42369",
    "latitude": 51.227884,
    "longitude": 7.18022,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Mama Malamo",
    "slug": "wuppertal-mama-malamo",
    "type": "restaurant",
    "cuisine": "Greek",
    "description": "",
    "address": "Uellendahler Straße 61",
    "city": "Wuppertal",
    "postalCode": "42107",
    "latitude": 51.268705,
    "longitude": 7.148398,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Taverne Knossos",
    "slug": "wuppertal-taverne-knossos",
    "type": "restaurant",
    "cuisine": "Greek",
    "description": "",
    "address": "",
    "city": "Wuppertal",
    "postalCode": "",
    "latitude": 51.288973,
    "longitude": 7.294039,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Bei Elisabeth und Lefti",
    "slug": "wuppertal-bei-elisabeth-und-lefti",
    "type": "restaurant",
    "cuisine": "Regional",
    "description": "",
    "address": "",
    "city": "Wuppertal",
    "postalCode": "",
    "latitude": 51.309244,
    "longitude": 7.103589,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 0,
        "open": 690,
        "close": 1320
      },
      {
        "day": 3,
        "open": 960,
        "close": 1320
      },
      {
        "day": 4,
        "open": 960,
        "close": 1320
      },
      {
        "day": 5,
        "open": 690,
        "close": 1320
      },
      {
        "day": 6,
        "open": 690,
        "close": 1320
      }
    ]
  },
  {
    "name": "El Rancho",
    "slug": "wuppertal-el-rancho",
    "type": "restaurant",
    "cuisine": "Steak House",
    "description": "",
    "address": "",
    "city": "Wuppertal",
    "postalCode": "",
    "latitude": 51.289919,
    "longitude": 7.046248,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Simons36",
    "slug": "wuppertal-simons36",
    "type": "restaurant",
    "cuisine": "Regional",
    "description": "",
    "address": "Simonsstraße 36",
    "city": "Wuppertal",
    "postalCode": "42117",
    "latitude": 51.248423,
    "longitude": 7.12944,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 0,
        "open": 720,
        "close": 1320
      },
      {
        "day": 2,
        "open": 720,
        "close": 1320
      },
      {
        "day": 3,
        "open": 720,
        "close": 1320
      },
      {
        "day": 4,
        "open": 720,
        "close": 1320
      },
      {
        "day": 5,
        "open": 720,
        "close": 1320
      },
      {
        "day": 6,
        "open": 720,
        "close": 1320
      }
    ]
  },
  {
    "name": "Apollo",
    "slug": "wuppertal-apollo",
    "type": "restaurant",
    "cuisine": "Greek",
    "description": "",
    "address": "",
    "city": "Wuppertal",
    "postalCode": "",
    "latitude": 51.289003,
    "longitude": 7.297156,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Bäckerei Evertzberg",
    "slug": "wuppertal-backerei-evertzberg",
    "type": "bakery",
    "cuisine": "",
    "description": "",
    "address": "Hahnerberger Straße 185",
    "city": "Wuppertal",
    "postalCode": "42349",
    "latitude": 51.220225,
    "longitude": 7.152547,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 1,
        "open": 330,
        "close": 1110
      },
      {
        "day": 2,
        "open": 330,
        "close": 1110
      },
      {
        "day": 3,
        "open": 330,
        "close": 1110
      },
      {
        "day": 4,
        "open": 330,
        "close": 1110
      },
      {
        "day": 5,
        "open": 330,
        "close": 1110
      }
    ]
  },
  {
    "name": "Indian Palace",
    "slug": "wuppertal-indian-palace",
    "type": "restaurant",
    "cuisine": "Indian",
    "description": "",
    "address": "Cronenberger Straße 150",
    "city": "Wuppertal",
    "postalCode": "42119",
    "latitude": 51.238982,
    "longitude": 7.146698,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 0,
        "open": 690,
        "close": 1350
      },
      {
        "day": 1,
        "open": 690,
        "close": 1350
      },
      {
        "day": 2,
        "open": 690,
        "close": 1350
      },
      {
        "day": 3,
        "open": 690,
        "close": 1350
      },
      {
        "day": 4,
        "open": 690,
        "close": 1350
      },
      {
        "day": 5,
        "open": 690,
        "close": 1350
      },
      {
        "day": 6,
        "open": 690,
        "close": 1350
      }
    ]
  },
  {
    "name": "Pizzeria Akropolis",
    "slug": "wuppertal-pizzeria-akropolis",
    "type": "restaurant",
    "cuisine": "Greek",
    "description": "",
    "address": "Tannenbergstraße 57",
    "city": "Wuppertal",
    "postalCode": "42103",
    "latitude": 51.250764,
    "longitude": 7.137742,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 0,
        "open": 840,
        "close": 1380
      },
      {
        "day": 1,
        "open": 660,
        "close": 1380
      },
      {
        "day": 2,
        "open": 660,
        "close": 1380
      },
      {
        "day": 3,
        "open": 660,
        "close": 1380
      },
      {
        "day": 4,
        "open": 660,
        "close": 1380
      },
      {
        "day": 5,
        "open": 660,
        "close": 1380
      },
      {
        "day": 6,
        "open": 660,
        "close": 1380
      }
    ]
  },
  {
    "name": "Oebel",
    "slug": "wuppertal-oebel",
    "type": "bakery",
    "cuisine": "",
    "description": "",
    "address": "",
    "city": "Wuppertal",
    "postalCode": "",
    "latitude": 51.249028,
    "longitude": 7.143146,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 0,
        "open": 480,
        "close": 780
      },
      {
        "day": 1,
        "open": 330,
        "close": 1080
      },
      {
        "day": 2,
        "open": 330,
        "close": 1080
      },
      {
        "day": 3,
        "open": 330,
        "close": 1080
      },
      {
        "day": 4,
        "open": 330,
        "close": 1080
      },
      {
        "day": 5,
        "open": 330,
        "close": 1080
      },
      {
        "day": 6,
        "open": 420,
        "close": 780
      }
    ]
  },
  {
    "name": "Bäckerei Schüren",
    "slug": "wuppertal-backerei-schuren",
    "type": "bakery",
    "cuisine": "",
    "description": "",
    "address": "Gerberstraße 30",
    "city": "Solingen",
    "postalCode": "42653",
    "latitude": 51.209693,
    "longitude": 7.073592,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Bäckerei Stöcker",
    "slug": "wuppertal-backerei-stocker",
    "type": "bakery",
    "cuisine": "",
    "description": "",
    "address": "",
    "city": "Wuppertal",
    "postalCode": "",
    "latitude": 51.20066,
    "longitude": 7.073745,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 1,
        "open": 540,
        "close": 1110
      },
      {
        "day": 2,
        "open": 540,
        "close": 1110
      },
      {
        "day": 3,
        "open": 540,
        "close": 1110
      },
      {
        "day": 4,
        "open": 540,
        "close": 1110
      },
      {
        "day": 5,
        "open": 540,
        "close": 1110
      },
      {
        "day": 6,
        "open": 600,
        "close": 840
      }
    ]
  },
  {
    "name": "Kamps",
    "slug": "wuppertal-kamps",
    "type": "bakery",
    "cuisine": "",
    "description": "",
    "address": "",
    "city": "Wuppertal",
    "postalCode": "",
    "latitude": 51.257336,
    "longitude": 7.144844,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 1,
        "open": 390,
        "close": 1080
      },
      {
        "day": 2,
        "open": 390,
        "close": 1080
      },
      {
        "day": 3,
        "open": 390,
        "close": 1080
      },
      {
        "day": 4,
        "open": 390,
        "close": 1080
      },
      {
        "day": 5,
        "open": 390,
        "close": 1080
      },
      {
        "day": 6,
        "open": 420,
        "close": 1020
      }
    ]
  },
  {
    "name": "Mor'n",
    "slug": "wuppertal-mor-n",
    "type": "restaurant",
    "cuisine": "Asian",
    "description": "",
    "address": "Herzogstraße 2",
    "city": "Wuppertal",
    "postalCode": "42103",
    "latitude": 51.257149,
    "longitude": 7.145825,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 1,
        "open": 630,
        "close": 1260
      },
      {
        "day": 2,
        "open": 630,
        "close": 1260
      },
      {
        "day": 3,
        "open": 630,
        "close": 1260
      },
      {
        "day": 4,
        "open": 630,
        "close": 1260
      },
      {
        "day": 5,
        "open": 630,
        "close": 1260
      },
      {
        "day": 6,
        "open": 630,
        "close": 1260
      }
    ]
  },
  {
    "name": "Die Zwei",
    "slug": "wuppertal-die-zwei",
    "type": "bakery",
    "cuisine": "",
    "description": "",
    "address": "",
    "city": "Wuppertal",
    "postalCode": "",
    "latitude": 51.257806,
    "longitude": 7.150916,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 1,
        "open": 480,
        "close": 1200
      },
      {
        "day": 2,
        "open": 480,
        "close": 1200
      },
      {
        "day": 3,
        "open": 480,
        "close": 1200
      },
      {
        "day": 4,
        "open": 480,
        "close": 1200
      },
      {
        "day": 5,
        "open": 480,
        "close": 1200
      },
      {
        "day": 6,
        "open": 480,
        "close": 1200
      }
    ]
  },
  {
    "name": "Road Stop",
    "slug": "wuppertal-road-stop",
    "type": "restaurant",
    "cuisine": "American",
    "description": "",
    "address": "",
    "city": "Wuppertal",
    "postalCode": "",
    "latitude": 51.302519,
    "longitude": 7.215056,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 0,
        "open": 720,
        "close": 1290
      },
      {
        "day": 1,
        "open": 960,
        "close": 1320
      },
      {
        "day": 2,
        "open": 960,
        "close": 1320
      },
      {
        "day": 3,
        "open": 960,
        "close": 1320
      },
      {
        "day": 4,
        "open": 960,
        "close": 1320
      },
      {
        "day": 5,
        "open": 720,
        "close": 1380
      },
      {
        "day": 6,
        "open": 720,
        "close": 1380
      }
    ]
  },
  {
    "name": "Al Howara",
    "slug": "wuppertal-al-howara",
    "type": "restaurant",
    "cuisine": "Arabic",
    "description": "",
    "address": "Bembergstraße 20",
    "city": "Wuppertal",
    "postalCode": "42103",
    "latitude": 51.256439,
    "longitude": 7.153712,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 0,
        "open": 1080,
        "close": 1380
      },
      {
        "day": 1,
        "open": 1080,
        "close": 1380
      },
      {
        "day": 2,
        "open": 1080,
        "close": 1380
      },
      {
        "day": 3,
        "open": 1080,
        "close": 1380
      },
      {
        "day": 4,
        "open": 1080,
        "close": 1380
      },
      {
        "day": 5,
        "open": 1080,
        "close": 1440
      },
      {
        "day": 6,
        "open": 1080,
        "close": 1440
      }
    ]
  },
  {
    "name": "Pizza Leoni",
    "slug": "wuppertal-pizza-leoni",
    "type": "restaurant",
    "cuisine": "Pizza",
    "description": "",
    "address": "",
    "city": "Wuppertal",
    "postalCode": "",
    "latitude": 51.286932,
    "longitude": 7.231791,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Eiscafé Colucci",
    "slug": "wuppertal-eiscafe-colucci",
    "type": "cafe",
    "cuisine": "Ice Cream",
    "description": "",
    "address": "Werléstraße 27",
    "city": "Wuppertal",
    "postalCode": "42289",
    "latitude": 51.271318,
    "longitude": 7.222488,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 0,
        "open": 600,
        "close": 1200
      },
      {
        "day": 1,
        "open": 600,
        "close": 1200
      },
      {
        "day": 2,
        "open": 600,
        "close": 1200
      },
      {
        "day": 3,
        "open": 600,
        "close": 1200
      },
      {
        "day": 4,
        "open": 600,
        "close": 1200
      },
      {
        "day": 5,
        "open": 600,
        "close": 1200
      },
      {
        "day": 6,
        "open": 600,
        "close": 1200
      }
    ]
  },
  {
    "name": "Uni Kneipe",
    "slug": "wuppertal-uni-kneipe",
    "type": "restaurant",
    "cuisine": "",
    "description": "",
    "address": "",
    "city": "Wuppertal",
    "postalCode": "",
    "latitude": 51.246294,
    "longitude": 7.147415,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 1,
        "open": 660,
        "close": 1260
      },
      {
        "day": 2,
        "open": 660,
        "close": 1260
      },
      {
        "day": 3,
        "open": 660,
        "close": 1260
      },
      {
        "day": 4,
        "open": 660,
        "close": 1260
      },
      {
        "day": 5,
        "open": 660,
        "close": 1260
      }
    ]
  },
  {
    "name": "Eiscafe Italia",
    "slug": "wuppertal-eiscafe-italia",
    "type": "cafe",
    "cuisine": "Ice Cream",
    "description": "",
    "address": "",
    "city": "Wuppertal",
    "postalCode": "",
    "latitude": 51.270769,
    "longitude": 7.125133,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Meson Alegria",
    "slug": "wuppertal-meson-alegria",
    "type": "restaurant",
    "cuisine": "Spanish",
    "description": "",
    "address": "Briller Straße 19",
    "city": "Wuppertal",
    "postalCode": "42105",
    "latitude": 51.255182,
    "longitude": 7.131281,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 0,
        "open": 1080,
        "close": 60
      },
      {
        "day": 2,
        "open": 1080,
        "close": 60
      },
      {
        "day": 3,
        "open": 1080,
        "close": 60
      },
      {
        "day": 4,
        "open": 1080,
        "close": 60
      },
      {
        "day": 5,
        "open": 1080,
        "close": 60
      },
      {
        "day": 6,
        "open": 1080,
        "close": 60
      }
    ]
  },
  {
    "name": "Gemüsepavillon Ardic",
    "slug": "wuppertal-gemusepavillon-ardic",
    "type": "grocery",
    "cuisine": "",
    "description": "",
    "address": "",
    "city": "Wuppertal",
    "postalCode": "",
    "latitude": 51.312032,
    "longitude": 7.088982,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 3,
        "open": 540,
        "close": 780
      },
      {
        "day": 6,
        "open": 540,
        "close": 780
      }
    ]
  },
  {
    "name": "Backshop Neviges",
    "slug": "wuppertal-backshop-neviges",
    "type": "bakery",
    "cuisine": "",
    "description": "",
    "address": "Elberfelder Straße 31",
    "city": "Wuppertal",
    "postalCode": "",
    "latitude": 51.31167,
    "longitude": 7.089135,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Graf Hardenberg",
    "slug": "wuppertal-graf-hardenberg",
    "type": "restaurant",
    "cuisine": "Regional",
    "description": "",
    "address": "",
    "city": "Wuppertal",
    "postalCode": "",
    "latitude": 51.31412,
    "longitude": 7.087112,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 0,
        "open": 900,
        "close": 1440
      },
      {
        "day": 2,
        "open": 900,
        "close": 1440
      },
      {
        "day": 3,
        "open": 900,
        "close": 1440
      },
      {
        "day": 4,
        "open": 900,
        "close": 1440
      },
      {
        "day": 5,
        "open": 900,
        "close": 1440
      },
      {
        "day": 6,
        "open": 900,
        "close": 1440
      }
    ]
  },
  {
    "name": "Evertzberg",
    "slug": "wuppertal-evertzberg",
    "type": "bakery",
    "cuisine": "",
    "description": "",
    "address": "",
    "city": "Wuppertal",
    "postalCode": "",
    "latitude": 51.302385,
    "longitude": 7.216349,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 0,
        "open": 420,
        "close": 780
      },
      {
        "day": 1,
        "open": 360,
        "close": 1080
      },
      {
        "day": 2,
        "open": 360,
        "close": 1080
      },
      {
        "day": 3,
        "open": 360,
        "close": 1080
      },
      {
        "day": 4,
        "open": 360,
        "close": 1080
      },
      {
        "day": 5,
        "open": 360,
        "close": 1080
      },
      {
        "day": 6,
        "open": 360,
        "close": 900
      }
    ]
  },
  {
    "name": "Thomas Röder Bäckerei",
    "slug": "wuppertal-thomas-roder-backerei",
    "type": "bakery",
    "cuisine": "",
    "description": "",
    "address": "",
    "city": "Wuppertal",
    "postalCode": "",
    "latitude": 51.287294,
    "longitude": 7.218109,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Gaststätte Nolzen",
    "slug": "wuppertal-gaststatte-nolzen",
    "type": "restaurant",
    "cuisine": "",
    "description": "",
    "address": "Talsperrenstraße 78",
    "city": "Wuppertal",
    "postalCode": "42369",
    "latitude": 51.221666,
    "longitude": 7.193549,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "le Cefateria",
    "slug": "wuppertal-le-cefateria",
    "type": "cafe",
    "cuisine": "Coffee",
    "description": "",
    "address": "",
    "city": "Wuppertal",
    "postalCode": "",
    "latitude": 51.220487,
    "longitude": 7.080476,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Saray Imbiss",
    "slug": "wuppertal-saray-imbiss",
    "type": "restaurant",
    "cuisine": "Turkish",
    "description": "",
    "address": "",
    "city": "Wuppertal",
    "postalCode": "",
    "latitude": 51.220577,
    "longitude": 7.080668,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Hans im Glück",
    "slug": "wuppertal-hans-im-gluck",
    "type": "restaurant",
    "cuisine": "Burger",
    "description": "",
    "address": "",
    "city": "Wuppertal",
    "postalCode": "42103",
    "latitude": 51.257288,
    "longitude": 7.142705,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Quermalerei",
    "slug": "wuppertal-quermalerei",
    "type": "cafe",
    "cuisine": "Coffee",
    "description": "",
    "address": "",
    "city": "Wuppertal",
    "postalCode": "",
    "latitude": 51.264791,
    "longitude": 7.151672,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 0,
        "open": 600,
        "close": 1320
      },
      {
        "day": 4,
        "open": 600,
        "close": 1320
      },
      {
        "day": 5,
        "open": 600,
        "close": 1320
      },
      {
        "day": 6,
        "open": 600,
        "close": 1320
      }
    ]
  },
  {
    "name": "Mazzino",
    "slug": "wuppertal-mazzino",
    "type": "cafe",
    "cuisine": "Coffee",
    "description": "",
    "address": "",
    "city": "Wuppertal",
    "postalCode": "",
    "latitude": 51.256331,
    "longitude": 7.146515,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Bernhard - Soulfood & Drinks",
    "slug": "wuppertal-bernhard-soulfood-and-drinks",
    "type": "restaurant",
    "cuisine": "Curry",
    "description": "",
    "address": "Luisenstraße 72",
    "city": "Wuppertal",
    "postalCode": "42103",
    "latitude": 51.257269,
    "longitude": 7.139241,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 1,
        "open": 720,
        "close": 900
      },
      {
        "day": 2,
        "open": 720,
        "close": 900
      },
      {
        "day": 3,
        "open": 720,
        "close": 900
      },
      {
        "day": 4,
        "open": 720,
        "close": 900
      }
    ]
  },
  {
    "name": "Back Treff",
    "slug": "wuppertal-back-treff",
    "type": "bakery",
    "cuisine": "",
    "description": "",
    "address": "",
    "city": "Wuppertal",
    "postalCode": "",
    "latitude": 51.31335,
    "longitude": 7.067074,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 0,
        "open": 450,
        "close": 690
      },
      {
        "day": 1,
        "open": 330,
        "close": 900
      },
      {
        "day": 2,
        "open": 330,
        "close": 900
      },
      {
        "day": 3,
        "open": 330,
        "close": 900
      },
      {
        "day": 4,
        "open": 330,
        "close": 900
      },
      {
        "day": 5,
        "open": 330,
        "close": 900
      },
      {
        "day": 6,
        "open": 360,
        "close": 720
      }
    ]
  },
  {
    "name": "Café Pergola",
    "slug": "wuppertal-cafe-pergola",
    "type": "cafe",
    "cuisine": "Coffee",
    "description": "",
    "address": "",
    "city": "Wuppertal",
    "postalCode": "",
    "latitude": 51.255043,
    "longitude": 7.136993,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Haus Eisenbach",
    "slug": "wuppertal-haus-eisenbach",
    "type": "restaurant",
    "cuisine": "",
    "description": "",
    "address": "Weinberg 6a",
    "city": "Wuppertal",
    "postalCode": "42109",
    "latitude": 51.273585,
    "longitude": 7.159596,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 1,
        "open": 1050,
        "close": 1350
      },
      {
        "day": 2,
        "open": 1050,
        "close": 1350
      },
      {
        "day": 3,
        "open": 1050,
        "close": 1350
      },
      {
        "day": 4,
        "open": 1050,
        "close": 1350
      },
      {
        "day": 5,
        "open": 1050,
        "close": 1350
      },
      {
        "day": 6,
        "open": 1050,
        "close": 1350
      }
    ]
  },
  {
    "name": "China Restaurant Am Asbruch",
    "slug": "wuppertal-china-restaurant-am-asbruch",
    "type": "restaurant",
    "cuisine": "Chinese",
    "description": "",
    "address": "",
    "city": "Wuppertal",
    "postalCode": "",
    "latitude": 51.295793,
    "longitude": 7.097442,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 0,
        "open": 690,
        "close": 1380
      }
    ]
  },
  {
    "name": "Esskultürk",
    "slug": "wuppertal-esskulturk",
    "type": "restaurant",
    "cuisine": "German, Turkish",
    "description": "",
    "address": "Besenbruchstraße 7",
    "city": "Wuppertal",
    "postalCode": "42285",
    "latitude": 51.261734,
    "longitude": 7.17433,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 0,
        "open": 1080,
        "close": 1290
      },
      {
        "day": 6,
        "open": 1080,
        "close": 1290
      }
    ]
  },
  {
    "name": "Mektup Sahne",
    "slug": "wuppertal-mektup-sahne",
    "type": "restaurant",
    "cuisine": "",
    "description": "",
    "address": "",
    "city": "Wuppertal",
    "postalCode": "",
    "latitude": 51.275129,
    "longitude": 7.223543,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  },
  {
    "name": "Jey Jey 's Tapas & mehr",
    "slug": "wuppertal-jey-jey-s-tapas-and-mehr",
    "type": "restaurant",
    "cuisine": "",
    "description": "",
    "address": "Aue 56",
    "city": "Wuppertal",
    "postalCode": "42103",
    "latitude": 51.254196,
    "longitude": 7.13738,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": [
      {
        "day": 0,
        "open": 1020,
        "close": 1380
      },
      {
        "day": 1,
        "open": 1020,
        "close": 1380
      },
      {
        "day": 2,
        "open": 1020,
        "close": 1380
      },
      {
        "day": 3,
        "open": 1020,
        "close": 1380
      },
      {
        "day": 4,
        "open": 1020,
        "close": 1380
      },
      {
        "day": 5,
        "open": 1020,
        "close": 1380
      },
      {
        "day": 6,
        "open": 1020,
        "close": 1380
      }
    ]
  },
  {
    "name": "Resumė",
    "slug": "wuppertal-resume",
    "type": "restaurant",
    "cuisine": "Steak House",
    "description": "",
    "address": "Aue 54",
    "city": "Wuppertal",
    "postalCode": "42103",
    "latitude": 51.254227,
    "longitude": 7.137527,
    "priceTier": 2,
    "region": "wuppertal",
    "hours": []
  }
]
